"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Navigasjon from "../components/Navigasjon";
import MittHjemDetaljer from "../components/MittHjemDetaljer";
import { createClient } from "../lib/supabase/client";
import { harPrivat, lesBruksomrade } from "../lib/bruksomrade";
import { hentBoliger, opprettBolig, type BoligData } from "../lib/boliger";
import { hentDokumenter, type Dokument } from "../lib/dokumenter";
import { hentVedlikeholdsoppgaver, type Vedlikeholdsdata } from "../lib/vedlikehold";
import { demoAltOmBoligen, lesAltOmBoligen } from "../lib/alt-om-boligen";
import { opprettBoligoverforing } from "../lib/boligoverforing";

type NyBolig={adresse:string;boligtype:string;byggeaar:string;areal:string;kjopsdato:string;kjopesum:string;markedsverdi:string};
const tom:NyBolig={adresse:"",boligtype:"Enebolig",byggeaar:"",areal:"",kjopsdato:"",kjopesum:"",markedsverdi:""};
const privateDokumentkategorier=new Set(["plantegning","boligbilde","kvittering","faktura","vedlikehold","takst","meglervurdering","samsvarserklaring","garanti","brukerveiledning"]);
const demoPrivatBolig:BoligData={id:"demo-privat-hjem",brukstype:"privat",adresse:"Eksempelveien 12, Bergen",boligtype:"Enebolig",byggeaar:"1958",areal:142,kjopsdato:"2021-06-15",kjopesum:5200000,markedsverdi:6100000};
const demoHjemDokumenter:Dokument[]=[
 {id:"demo-hjem-dok-1",boligId:"demo-privat-hjem",navn:"Plantegning 1. etasje",kategori:"plantegning",ar:2021,dokumentdato:"2021-06-15",notat:"Plantegning ved kjøp",filsti:"",filnavn:"plantegning-1-etasje.pdf",filtype:"application/pdf",filstorrelse:420000,createdAt:"2021-06-15T12:00:00Z",kilde:"arkiv"},
 {id:"demo-hjem-dok-2",boligId:"demo-privat-hjem",navn:"Tilstandsrapport",kategori:"takst",ar:2021,dokumentdato:"2021-05-20",notat:"Rapport fra boligkjøpet",filsti:"",filnavn:"tilstandsrapport.pdf",filtype:"application/pdf",filstorrelse:2100000,createdAt:"2021-05-20T12:00:00Z",kilde:"arkiv"},
 {id:"demo-hjem-dok-3",boligId:"demo-privat-hjem",navn:"Førbilde av bad",kategori:"vedlikehold",ar:2024,dokumentdato:"2024-02-02",notat:"Før oppussing",filsti:"",filnavn:"bad-for.jpg",filtype:"image/jpeg",filstorrelse:1300000,createdAt:"2024-02-02T12:00:00Z",kilde:"arkiv"},
 {id:"demo-hjem-dok-4",boligId:"demo-privat-hjem",navn:"Etterbilde av bad",kategori:"vedlikehold",ar:2024,dokumentdato:"2024-05-18",notat:"Etter oppussing",filsti:"",filnavn:"bad-etter.jpg",filtype:"image/jpeg",filstorrelse:1450000,createdAt:"2024-05-18T12:00:00Z",kilde:"arkiv"},
 {id:"demo-hjem-dok-5",boligId:"demo-privat-hjem",navn:"Samsvarserklæring bad",kategori:"samsvarserklaring",ar:2024,dokumentdato:"2024-05-20",notat:"Elektrisk arbeid",filsti:"",filnavn:"samsvarserklaring.pdf",filtype:"application/pdf",filstorrelse:360000,createdAt:"2024-05-20T12:00:00Z",kilde:"arkiv"},
 {id:"demo-hjem-dok-6",boligId:"demo-privat-hjem",navn:"Forsikringsbevis",kategori:"forsikring",ar:2026,dokumentdato:"2026-01-10",notat:"Gjeldende boligforsikring",filsti:"",filnavn:"forsikringsbevis.pdf",filtype:"application/pdf",filstorrelse:280000,createdAt:"2026-01-10T12:00:00Z",kilde:"arkiv"},
];
const demoHjemOppgaver:Vedlikeholdsdata[]=[
 {id:"demo-hjem-ved-1",boligId:"demo-privat-hjem",boligAdresse:"Eksempelveien 12, Bergen",tittel:"Kontroller røykvarslere",navn:"Kontroller røykvarslere",frist:"2026-09-25",status:"planlagt",prioritet:"hoy"},
 {id:"demo-hjem-ved-2",boligId:"demo-privat-hjem",boligAdresse:"Eksempelveien 12, Bergen",tittel:"Rens takrenner",navn:"Rens takrenner",frist:"2026-10-15",status:"planlagt",prioritet:"normal"},
 {id:"demo-hjem-ved-3",boligId:"demo-privat-hjem",boligAdresse:"Eksempelveien 12, Bergen",tittel:"Beis terrassen",navn:"Beis terrassen",frist:"2027-05-15",status:"planlagt",prioritet:"lav"},
];
export default function MittHjem(){
 const router=useRouter();const search=useSearchParams();const supabase=useMemo(()=>createClient(),[]);
 const [boliger,setBoliger]=useState<BoligData[]>([]);const [valgtId,setValgtId]=useState("");const [dokumenter,setDokumenter]=useState<Dokument[]>([]);const [oppgaver,setOppgaver]=useState<Vedlikeholdsdata[]>([]);const [innlogget,setInnlogget]=useState(false);const [laster,setLaster]=useState(true);const [feil,setFeil]=useState("");const [visNy,setVisNy]=useState(false);const [ny,setNy]=useState<NyBolig>(tom);const [lagrer,setLagrer]=useState(false);
 const [visOverfor,setVisOverfor]=useState(false);const [mottaker,setMottaker]=useState("");const [bekreftet,setBekreftet]=useState(false);const [valgteDok,setValgteDok]=useState<string[]>([]);const [lenke,setLenke]=useState("");
 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser();if(!data.user){setInnlogget(false);setBoliger([demoPrivatBolig]);setDokumenter(demoHjemDokumenter);setOppgaver(demoHjemOppgaver);setValgtId(demoPrivatBolig.id);setLaster(false);return;}setInnlogget(true);const modus=lesBruksomrade(data.user);if(!modus){router.replace("/velg-bruksomrade");return;}if(!harPrivat(modus)){setFeil("Privat bolig er ikke aktivert. Du kan endre bruksområde under Min konto.");setLaster(false);return;}try{const [alle,dok,ved]=await Promise.all([hentBoliger(),hentDokumenter(),hentVedlikeholdsoppgaver()]);const privateBoliger=alle.filter(b=>String(b.brukstype||"")==="privat");setBoliger(privateBoliger);setDokumenter(dok);setOppgaver(ved);setValgtId(String(privateBoliger[0]?.id||""));setVisNy(privateBoliger.length===0);}catch{setFeil("Kunne ikke hente boliginformasjonen.");}finally{setLaster(false);}})();},[router,supabase]);
 const valgt=boliger.find(b=>String(b.id)===valgtId)||null;const alt=valgt?(innlogget?lesAltOmBoligen(valgt):demoAltOmBoligen(valgt)):null;const boligDok=dokumenter.filter(d=>d.boligId===valgtId);const delbareDok=boligDok.filter(d=>privateDokumentkategorier.has(d.kategori));const boligOppgaver=oppgaver.filter(o=>o.boligId===valgtId);const aktive=boligOppgaver.filter(o=>String(o.status||"")!=="ferdig");
 const komplett=useMemo(()=>{if(!valgt||!alt)return 0;const sjekk=[valgt.adresse,valgt.boligtype,alt.generell.byggeaar,alt.generell.totalareal,alt.teknisk.hovedstoppekran,alt.teknisk.sikringsskap,alt.rom.length,alt.uteomrader.length,alt.utstyr.length,alt.oppussing.length,boligDok.length];return Math.round(sjekk.filter(Boolean).length/sjekk.length*100);},[valgt,alt,boligDok.length]);
 async function lagreNy(e:FormEvent){e.preventDefault();if(!ny.adresse.trim())return;setLagrer(true);setFeil("");try{await opprettBolig({brukstype:"privat",adresse:ny.adresse.trim(),boligtype:ny.boligtype,byggeaar:ny.byggeaar,areal:Number(ny.areal)||0,kjopsdato:ny.kjopsdato,kjopesum:Number(ny.kjopesum)||0,markedsverdi:Number(ny.markedsverdi)||0,restlaan:0,manedsleie:0});const alle=await hentBoliger();const p=alle.filter(b=>String(b.brukstype||"")==="privat");setBoliger(p);setValgtId(String(p[p.length-1]?.id||""));setVisNy(false);setNy(tom);}catch{setFeil("Kunne ikke opprette boligen.");}finally{setLagrer(false);}}
 async function lagOverforing(){if(!valgt||!/^\S+@\S+\.\S+$/.test(mottaker)||!bekreftet)return;setLagrer(true);setFeil("");try{const url=await opprettBoligoverforing(valgt,mottaker,{rom:true,oppussing:true,teknisk:true,utstyr:true,sikkerhet:true,dokumentIder:valgteDok});setLenke(url);}catch(e){setFeil(e instanceof Error?e.message:"Kunne ikke opprette overføringen.");}finally{setLagrer(false);}}
 if(laster)return <main className="min-h-screen bg-stone-50"><Navigasjon/><p className="p-12 text-center">Laster hjemmet ditt…</p></main>;
 return <main className="min-h-screen bg-stone-50 text-slate-900"><Navigasjon/><header className="bg-gradient-to-br from-emerald-950 via-slate-900 to-teal-900 px-4 py-10 text-white"><div className="mx-auto flex max-w-6xl flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold tracking-wider text-emerald-300">PRIVAT BOLIG</p><h1 className="mt-2 text-4xl font-bold">Mitt hjem</h1><p className="mt-3 max-w-2xl text-slate-300">Boligens informasjon, historie og neste oppgaver samlet på ett sted.</p></div>{boliger.length>0&&<button onClick={()=>setVisNy(true)} className="rounded-xl bg-white/10 px-5 py-3 font-semibold ring-1 ring-white/20 hover:bg-white/20">+ Legg til privat bolig</button>}</div></header>
 <div className="mx-auto max-w-6xl px-4 py-8">{!innlogget&&<div className="mb-5 flex flex-col gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 sm:flex-row sm:items-center sm:justify-between"><p><strong>Du ser et eksempel på Mitt hjem.</strong> Opprett konto for å registrere din egen bolig.</p><Link href="/logg-inn" className="shrink-0 font-bold text-emerald-800">Opprett konto →</Link></div>}{search.get("overfort")==="ja"&&<p className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">Boligmappen er mottatt og ligger nå under Mitt hjem.</p>}{feil&&<p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{feil}</p>}
 {visNy?<section className="rounded-3xl bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-wider text-emerald-700">NYTT HJEM</p><h2 className="mt-2 text-2xl font-bold">Registrer privat bolig</h2></div>{boliger.length>0&&<button onClick={()=>setVisNy(false)} className="text-sm font-semibold text-slate-500">Avbryt</button>}</div><form onSubmit={lagreNy} className="mt-6 grid gap-4 sm:grid-cols-2">{([['Adresse','adresse','Stadionveien 16'],['Byggeår','byggeaar','1958'],['Areal (m²)','areal','142'],['Kjøpsdato','kjopsdato','']] as const).map(([label,key,placeholder])=><label key={key} className="text-sm font-semibold">{label}<input type={key==='kjopsdato'?'date':'text'} required={key==='adresse'} value={ny[key]} placeholder={placeholder} onChange={e=>setNy({...ny,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 font-normal outline-none focus:border-emerald-500"/></label>)}<label className="text-sm font-semibold">Boligtype<select value={ny.boligtype} onChange={e=>setNy({...ny,boligtype:e.target.value})} className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 font-normal"><option>Enebolig</option><option>Leilighet</option><option>Rekkehus</option><option>Tomannsbolig</option><option>Fritidsbolig</option></select></label><label className="text-sm font-semibold">Kjøpesum (valgfritt)<input inputMode="numeric" value={ny.kjopesum} onChange={e=>setNy({...ny,kjopesum:e.target.value})} className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Egen markedsverdi (valgfritt)<input inputMode="numeric" value={ny.markedsverdi} onChange={e=>setNy({...ny,markedsverdi:e.target.value})} className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 font-normal"/></label><button disabled={lagrer} className="rounded-xl bg-emerald-500 px-6 py-3 font-bold text-white disabled:opacity-50 sm:col-span-2 sm:justify-self-start">{lagrer?"Lagrer…":"Opprett Mitt hjem"}</button></form></section>:valgt&&alt?<><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><select value={valgtId} onChange={e=>setValgtId(e.target.value)} className="rounded-xl border border-stone-300 bg-white px-4 py-3 font-semibold">{boliger.map(b=><option key={b.id} value={b.id}>{String(b.adresse||"Privat bolig")}</option>)}</select><Link href={`/alt-om-boligen?bolig=${valgt.id}&rediger=1`} className="rounded-xl bg-emerald-500 px-5 py-3 text-center font-bold text-white">Rediger boligen</Link></div>
 <section className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="bg-gradient-to-r from-emerald-100 via-stone-100 to-sky-100 p-7 sm:p-10"><p className="text-sm font-semibold text-emerald-800">{String(valgt.boligtype||"Privat bolig")}</p><h2 className="mt-2 text-3xl font-bold sm:text-4xl">{String(valgt.adresse||"Mitt hjem")}</h2><p className="mt-3 text-slate-600">{[alt.generell.totalareal&&`${alt.generell.totalareal} m²`,alt.generell.byggeaar&&`Byggeår ${alt.generell.byggeaar}`,alt.generell.soverom&&`${alt.generell.soverom} soverom`].filter(Boolean).join(" · ")||"Legg inn boligens grunninformasjon"}</p><div className="mt-6 max-w-md"><div className="flex justify-between text-sm font-semibold"><span>Boligmappen er {komplett}% komplett</span><span>{komplett}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-emerald-500" style={{width:`${komplett}%`}}/></div></div></div></section>
 <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Tall tittel="Rom" verdi={alt.rom.length} tekst="med materialinfo"/><Tall tittel="Oppussinger" verdi={alt.oppussing.length} tekst="registrerte hendelser"/><Tall tittel="Dokumenter" verdi={boligDok.length} tekst="filer knyttet til boligen"/><Tall tittel="På planen" verdi={aktive.length} tekst="vedlikeholdsoppgaver"/></div>
 <div className="mt-6 grid gap-5 lg:grid-cols-3"><Kort tittel="Neste på planen"><p className="text-lg font-bold">{String(aktive[0]?.tittel||aktive[0]?.navn||"Ingen kommende oppgaver")}</p><Link href="/vedlikehold" className="mt-4 inline-block font-semibold text-emerald-700">Åpne vedlikehold →</Link></Kort><Kort tittel="Siste oppussing"><p className="text-lg font-bold">{alt.oppussing[alt.oppussing.length-1]?.tittel||"Ingen oppussing registrert"}</p><Link href={`/alt-om-boligen?bolig=${valgt.id}`} className="mt-4 inline-block font-semibold text-emerald-700">Se bolighistorikken →</Link></Kort><Kort tittel="Garantier"><p className="text-lg font-bold">{alt.garantier.length} registrerte garantier</p><Link href="/garantier" className="mt-4 inline-block font-semibold text-emerald-700">Se garantier og kvitteringer →</Link></Kort></div>
 <MittHjemDetaljer data={alt} oppgaver={aktive} dokumenter={boligDok}/>
 <section className="mt-6 rounded-3xl border border-emerald-200 bg-emerald-50 p-6 sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold tracking-wider text-emerald-800">VED SALG</p><h2 className="mt-2 text-2xl font-bold">Digital boligoverlevering</h2><p className="mt-2 max-w-2xl text-slate-600">Send boligens praktiske informasjon og historikk til kjøperen. Du velger selv hvilke dokumenter som skal følge med. Private notater og sensitiv informasjon deles ikke.</p></div><button onClick={()=>{setVisOverfor(!visOverfor);setValgteDok(delbareDok.map(d=>d.id));}} className="shrink-0 rounded-xl bg-slate-900 px-5 py-3 font-bold text-white">{visOverfor?"Lukk":"Overfør boligmappe"}</button></div>{visOverfor&&<div className="mt-6 rounded-2xl bg-white p-5"><label className="text-sm font-semibold">Kjøperens e-post<input type="email" value={mottaker} onChange={e=>setMottaker(e.target.value)} placeholder="kjoper@eksempel.no" className="mt-2 w-full rounded-xl border border-stone-300 px-4 py-3 font-normal"/></label><div className="mt-5"><p className="font-semibold">Dokumenter som skal følge boligen</p><div className="mt-2 max-h-48 space-y-2 overflow-y-auto">{delbareDok.length?delbareDok.map(d=><label key={d.id} className="flex items-center gap-3 rounded-lg bg-stone-50 p-3 text-sm"><input type="checkbox" checked={valgteDok.includes(d.id)} onChange={e=>setValgteDok(e.target.checked?[...valgteDok,d.id]:valgteDok.filter(id=>id!==d.id))}/><span>{d.navn}</span></label>):<p className="text-sm text-slate-500">Ingen delbare dokumenter er registrert.</p>}</div></div><label className="mt-5 flex items-start gap-3 text-sm text-slate-700"><input type="checkbox" checked={bekreftet} onChange={e=>setBekreftet(e.target.checked)} className="mt-1"/><span>Jeg har kontrollert innholdet og bekrefter at det ikke inneholder sensitive personopplysninger eller sikkerhetskoder.</span></label>{lenke?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold text-emerald-900">Invitasjonslenken er klar</p><input readOnly value={lenke} className="mt-2 w-full rounded-lg border bg-white px-3 py-2 text-sm"/><div className="mt-3 flex flex-wrap gap-3"><button onClick={()=>navigator.clipboard.writeText(lenke)} className="font-semibold text-emerald-800">Kopier lenke</button><a href={`mailto:${encodeURIComponent(mottaker)}?subject=${encodeURIComponent("Boligmappen for "+String(valgt.adresse||"boligen"))}&body=${encodeURIComponent("Hei! Her kan du motta boligmappen: "+lenke)}`} className="font-semibold text-emerald-800">Åpne e-post</a></div></div>:<button onClick={lagOverforing} disabled={lagrer||!bekreftet||!/^\S+@\S+\.\S+$/.test(mottaker)} className="mt-5 rounded-xl bg-emerald-500 px-6 py-3 font-bold text-white disabled:opacity-40">{lagrer?"Oppretter…":"Lag sikker invitasjon"}</button>}</div>}</section></>:null}</div></main>;
}
function Tall({tittel,verdi,tekst}:{tittel:string;verdi:number;tekst:string}){return <div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{tittel}</p><p className="mt-2 text-3xl font-bold">{verdi}</p><p className="mt-1 text-xs text-slate-500">{tekst}</p></div>}
function Kort({tittel,children}:{tittel:string;children:React.ReactNode}){return <section className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="mb-4 text-sm font-bold uppercase tracking-wider text-slate-500">{tittel}</h3>{children}</section>}
