import type { Leietaker } from "./leietakere";
import type { BoligData } from "./boliger";
import type { Vedlikeholdsdata } from "./vedlikehold";

const ar = new Date().getFullYear();

export const DEMO_BOLIGER: BoligData[] = [
  {
    id: "demo-bolig-1",
    adresse: "Eksempelveien 12, Bergen",
    boligtype: "Leilighet",
    kjopesum: 3_450_000,
    kjopskostnader: 105_000,
    markedsverdi: 4_250_000,
    restlaan: 2_150_000,
    rente: 5.1,
    nedbetalingstid: 24,
    manedsleie: 23_000,
    ledighet: 2,
    felleskostnader: 2_150,
    felleskostnaderHarFellesgjeld: false,
    kommunaleAvgifter: 14_500,
    stromInternett: 1_200,
    vedlikehold: 12_000,
    andreKostnader: 4_000,
    skattepliktig: true,
    bruttoyield: 8,
    nettoyield: 5.2,
    kontantstrom: 4_850,
    egenkapitalverdi: 2_100_000,
    verdistigning: 695_000,
    belaningsgrad: 50.6,
  },
  {
    id: "demo-bolig-2",
    adresse: "Fjordgata 8, Bergen",
    boligtype: "Leilighet",
    kjopesum: 4_100_000,
    kjopskostnader: 125_000,
    markedsverdi: 4_750_000,
    restlaan: 2_900_000,
    rente: 5.25,
    nedbetalingstid: 27,
    manedsleie: 27_500,
    ledighet: 3,
    felleskostnader: 3_400,
    felleskostnaderHarFellesgjeld: true,
    kommunaleAvgifter: 12_000,
    stromInternett: 1_500,
    vedlikehold: 15_000,
    andreKostnader: 5_500,
    skattepliktig: true,
    bruttoyield: 8.05,
    nettoyield: 5.35,
    kontantstrom: 4_150,
    egenkapitalverdi: 1_850_000,
    verdistigning: 525_000,
    belaningsgrad: 61.1,
  },
  {
    id: "demo-bolig-3",
    adresse: "Solbakken 21, Trondheim",
    boligtype: "Rekkehus",
    kjopesum: 3_800_000,
    kjopskostnader: 120_000,
    markedsverdi: 4_300_000,
    restlaan: 2_400_000,
    rente: 5.15,
    nedbetalingstid: 25,
    manedsleie: 24_500,
    ledighet: 4,
    felleskostnader: 950,
    felleskostnaderHarFellesgjeld: false,
    kommunaleAvgifter: 19_500,
    stromInternett: 1_350,
    vedlikehold: 18_000,
    andreKostnader: 4_500,
    skattepliktig: true,
    bruttoyield: 7.74,
    nettoyield: 5.2,
    kontantstrom: 4_400,
    egenkapitalverdi: 1_900_000,
    verdistigning: 380_000,
    belaningsgrad: 55.8,
  },
  {
    id: "demo-bolig-4",
    adresse: "Parkveien 5, Stavanger",
    boligtype: "Tomannsbolig",
    kjopesum: 5_200_000,
    kjopskostnader: 155_000,
    markedsverdi: 5_850_000,
    restlaan: 3_250_000,
    rente: 5.05,
    nedbetalingstid: 28,
    manedsleie: 31_000,
    ledighet: 2,
    felleskostnader: 0,
    felleskostnaderHarFellesgjeld: false,
    kommunaleAvgifter: 24_000,
    stromInternett: 1_800,
    vedlikehold: 22_000,
    andreKostnader: 6_000,
    skattepliktig: true,
    bruttoyield: 7.15,
    nettoyield: 5.25,
    kontantstrom: 5_250,
    egenkapitalverdi: 2_600_000,
    verdistigning: 495_000,
    belaningsgrad: 55.6,
  },
];

export const DEMO_LEIETAKERE: Leietaker[] = [
  {
    id: "demo-leietaker-1",
    boligId: "demo-bolig-1",
    navn: "Ola Nordmann",
    telefon: "000 00 000",
    epost: "ola.nordmann@example.com",
    startdato: `${ar}-01-01`,
    sluttdato: `${ar}-12-31`,
    manedsleie: 23_000,
    forfallsdag: 1,
    depositumsstatus: "betalt",
    status: "aktiv",
    oppsigelsesfrist: 3,
    notat: "Eksempel på aktiv leietaker.",
    kontraktSti: "demo/ola-nordmann.pdf",
    kontraktFilnavn: "eksempel-leiekontrakt.pdf",
    kontraktLastetOpp: `${ar}-01-02T10:00:00.000Z`,
  },
  {
    id: "demo-leietaker-2",
    boligId: "demo-bolig-2",
    navn: "Kari Nordmann",
    telefon: "000 00 001",
    epost: "kari.nordmann@example.com",
    startdato: `${ar}-02-01`,
    sluttdato: `${ar + 1}-01-31`,
    manedsleie: 27_500,
    forfallsdag: 1,
    depositumsstatus: "betalt",
    status: "aktiv",
    oppsigelsesfrist: 3,
    notat: "Eksempeldata – ikke en virkelig person.",
    kontraktSti: "",
    kontraktFilnavn: "",
    kontraktLastetOpp: "",
  },
  {
    id: "demo-leietaker-3",
    boligId: "demo-bolig-3",
    navn: "Per Hansen",
    telefon: "000 00 002",
    epost: "per.hansen@example.com",
    startdato: `${ar - 1}-08-01`,
    sluttdato: "",
    manedsleie: 24_500,
    forfallsdag: 1,
    depositumsstatus: "betalt",
    status: "aktiv",
    oppsigelsesfrist: 3,
    notat: "Tidsubestemt eksempelavtale.",
    kontraktSti: "",
    kontraktFilnavn: "",
    kontraktLastetOpp: "",
  },
  {
    id: "demo-leietaker-4",
    boligId: "demo-bolig-4",
    navn: "Nora Eksempel",
    telefon: "000 00 003",
    epost: "nora.eksempel@example.com",
    startdato: `${ar}-03-01`,
    sluttdato: `${ar + 1}-02-28`,
    manedsleie: 31_000,
    forfallsdag: 1,
    depositumsstatus: "venter",
    status: "aktiv",
    oppsigelsesfrist: 3,
    notat: "Eksempeldata – ikke en virkelig person.",
    kontraktSti: "",
    kontraktFilnavn: "",
    kontraktLastetOpp: "",
  },
];

export const DEMO_VEDLIKEHOLD: Vedlikeholdsdata[] = [
  {
    id: "demo-vedlikehold-1",
    boligId: "demo-bolig-1",
    boligAdresse: "Eksempelveien 12, Bergen",
    tittel: "Kontroller røykvarslere",
    prioritet: "normal",
    startdato: `${ar}-09-01`,
    frist: `${ar}-10-01`,
    kostnad: 800,
    status: "planlagt",
    notat: "Årlig kontroll og bytte av batterier.",
    opprettet: `${ar}-08-10T09:00:00.000Z`,
  },
  {
    id: "demo-vedlikehold-2",
    boligId: "demo-bolig-2",
    boligAdresse: "Fjordgata 8, Bergen",
    tittel: "Service på varmtvannsbereder",
    prioritet: "hoy",
    startdato: `${ar}-08-20`,
    frist: `${ar}-09-15`,
    kostnad: 3_500,
    status: "pagar",
    notat: "Avtale med rørlegger er bestilt.",
    opprettet: `${ar}-08-12T11:00:00.000Z`,
  },
  {
    id: "demo-vedlikehold-3",
    boligId: "demo-bolig-3",
    boligAdresse: "Solbakken 21, Trondheim",
    tittel: "Maling av stue",
    prioritet: "lav",
    startdato: `${ar}-05-10`,
    frist: `${ar}-05-20`,
    kostnad: 7_500,
    status: "ferdig",
    notat: "Ferdig vedlikehold som vises i årsrapporten.",
    opprettet: `${ar}-04-15T08:00:00.000Z`,
  },
];

export function sendTilInnlogging() {
  if (typeof window !== "undefined") {
    window.location.assign("/logg-inn");
  }
}
