"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "../lib/supabase/client";
import { lesBruksomrade, type Bruksomrade } from "../lib/bruksomrade";
import ForsidePortefolje from "./ForsidePortefolje";

export default function ForsideInnhold() {
  const [modus, setModus] = useState<Bruksomrade | null>(null);
  const [innlogget, setInnlogget] = useState(false);
  const [laster, setLaster] = useState(true);
  useEffect(() => {
    const supabase = createClient(); let aktiv = true;
    const oppdater = (bruker: Parameters<typeof lesBruksomrade>[0]) => { if (aktiv) { setInnlogget(Boolean(bruker)); setModus(lesBruksomrade(bruker)); setLaster(false); } };
    supabase.auth.getUser().then(({ data }) => oppdater(data.user));
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_hendelse, sesjon) => oppdater(sesjon?.user ?? null));
    return () => { aktiv = false; subscription.unsubscribe(); };
  }, []);
  if (laster) return <div className="min-h-[70vh] bg-slate-950" />;
  if (!innlogget) return <OffentligForside />;
  if (!modus) return <VelgForside />;
  if (modus === "privat") return <PrivatForside />;
  if (modus === "begge") return <BeggeForside />;
  return <UtleieForside />;
}

function PrivatForside() { return <>
  <section className="bg-gradient-to-br from-emerald-950 via-slate-900 to-teal-900 px-4 py-20 text-white sm:px-6 sm:py-28"><div className="mx-auto max-w-6xl"><p className="font-semibold text-emerald-300">DITT DIGITALE SERVICEHEFTE</p><h1 className="mt-4 max-w-3xl text-4xl font-bold leading-tight sm:text-6xl">Ta vare på hjemmet og historien som følger det</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Samle rom, materialer, oppussing, vedlikehold, garantier og dokumenter – uten utleieinformasjon du ikke trenger.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/mitt-hjem" className="knapp-lys">Åpne Mitt hjem</Link><Link href="/alt-om-boligen" className="knapp-ramme">Se boligmappen</Link></div></div></section>
  <Veileder privat />
  <section className="bg-stone-50 px-4 py-12 sm:px-6 sm:py-16"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-2 lg:grid-cols-4"><Kort tittel="Boligmappen" tekst="Teknisk informasjon, installasjoner og uteområder." lenke="/alt-om-boligen"/><Kort tittel="Rom" tekst="Farger, materialer og notater for hvert rom." lenke="/rom"/><Kort tittel="Vedlikehold" tekst="Se hva som bør gjøres og hva som allerede er utført." lenke="/vedlikehold"/><Kort tittel="Dokumenter" tekst="Kvitteringer, garantier, forsikringer og kontakter." lenke="/dokumentarkiv"/></div></section>
</>; }

function UtleieForside() { return <>
  <section className="bg-slate-950 px-4 py-16 text-white sm:px-6 sm:py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1fr_.9fr]"><div><p className="font-semibold text-emerald-400">DIN UTLEIEPORTEFØLJE</p><h1 className="mt-4 text-4xl font-bold leading-tight sm:text-6xl">Kontroll på boliger, leietakere og økonomi</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Følg porteføljen, registrer husleie og kostnader, planlegg vedlikehold og bygg årsrapporten gjennom året.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/oversikt" className="knapp-lys">Åpne oversikten</Link><Link href="/boliger" className="knapp-ramme">Mine boliger</Link></div></div><ForsidePortefolje /></div></section>
  <Veileder />
  <section className="px-4 py-12 sm:px-6 sm:py-16"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3"><Kort tittel="Leietakere" tekst="Leieforhold og kontraktsperioder koblet til riktig bolig." lenke="/leietakere"/><Kort tittel="Inntekter og utgifter" tekst="Registrer faktiske betalinger og bilag gjennom året." lenke="/okonomi"/><Kort tittel="Årsrapport" tekst="Få samlet underlag til skattemeldingen per bolig og år." lenke="/skatterapport"/></div></section>
</>; }

function BeggeForside() { return <section className="min-h-[75vh] bg-slate-950 px-4 py-20 text-white sm:px-6"><div className="mx-auto max-w-6xl"><p className="text-center font-semibold text-emerald-400">VELG OMRÅDE</p><h1 className="mt-3 text-center text-4xl font-bold sm:text-5xl">Hva vil du åpne?</h1><p className="mx-auto mt-4 max-w-2xl text-center text-lg text-slate-300">Du har tilgang til både privatboligen og utleieporteføljen.</p><div className="mt-10 grid gap-6 md:grid-cols-2"><Omrade merke="PRIVAT BOLIG" tittel="Mitt hjem" tekst="Bolighistorikk, rom, vedlikehold, garantier og dokumenter." lenke="/mitt-hjem"/><Omrade merke="UTLEIE" tittel="Utleieoversikt" tekst="Boliger, leietakere, økonomi, kontrakter og årsrapport." lenke="/oversikt"/></div></div></section>; }

function VelgForside() { return <section className="min-h-[75vh] bg-stone-50 px-4 py-24 text-center"><h1 className="text-4xl font-bold">Velg hvordan du vil bruke Eiendomsoversikten</h1><p className="mx-auto mt-4 max-w-xl text-lg text-slate-600">Velg privat bolig, utleie eller begge deler. Du kan endre valget senere.</p><Link href="/velg-bruksomrade" className="mt-8 inline-block rounded-xl bg-emerald-500 px-7 py-3 font-bold text-white">Velg bruksområde</Link></section>; }

function OffentligForside() { return <>
  <section className="bg-slate-950 px-4 py-20 text-white sm:px-6 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><p className="font-semibold text-emerald-400">FOR BOLIGEIERE OG UTLEIERE</p><h1 className="mt-4 max-w-3xl text-4xl font-bold leading-tight sm:text-6xl">Full kontroll på boligen – på ett sted</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Samle boliginformasjon, oppussing, vedlikehold og dokumenter. Leier du ut, får du også kontroll på leietakere, økonomi, kontrakter og skatt.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/logg-inn" className="knapp-lys">Kom i gang gratis</Link><a href="#velg" className="knapp-ramme">Se hva som passer deg</a></div></div><div className="rounded-3xl border border-white/10 bg-white/5 p-5 shadow-2xl"><div className="rounded-2xl bg-stone-50 p-6 text-slate-900"><p className="text-xs font-bold tracking-wider text-emerald-700">EKSEMPEL · MITT HJEM</p><h2 className="mt-2 text-2xl font-bold">Eksempelveien 12</h2><p className="mt-1 text-sm text-slate-500">Enebolig · 142 m² · Byggeår 1958</p><div className="mt-5 grid grid-cols-2 gap-3"><Mini tittel="Neste oppgave" verdi="Røykvarsler · 18 dager"/><Mini tittel="Siste oppussing" verdi="Nytt bad · 2024"/><Mini tittel="Dokumenter" verdi="24 filer"/><Mini tittel="Garantier" verdi="3 aktive"/></div></div></div></div></section>
  <section id="velg" className="bg-stone-50 px-4 py-16 sm:px-6 sm:py-24"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="font-semibold text-emerald-700">ÉN TJENESTE – TO OPPLEVELSER</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Velg det som passer deg</h2></div><div className="mt-10 grid gap-6 lg:grid-cols-2"><Maalgruppe merke="PRIVAT BOLIG" tittel="Et digitalt servicehefte for hjemmet" punkter={["Rom, farger og materialer","Oppussing og vedlikehold","Garantier og dokumenter","Boligoverlevering ved salg"]}/><Maalgruppe merke="UTLEIE" tittel="Komplett utleieoversikt" punkter={["Boliger, leietakere og kontrakter","Inntekter og utgifter","Vedlikehold og kalender","Årsrapport og skatteunderlag"]}/></div></div></section>
</>; }

function Mini({tittel,verdi}:{tittel:string;verdi:string}) { return <div className="rounded-xl bg-white p-3 shadow-sm"><p className="text-xs text-slate-500">{tittel}</p><p className="mt-1 text-sm font-bold">{verdi}</p></div>; }
function Veileder({ privat = false }: { privat?: boolean }) { const steg = privat ? [{ tittel: "1. Start i Mitt hjem", tekst: "Se historikk og kommende oppgaver.", lenke: "/mitt-hjem" }, { tittel: "2. Fyll inn det viktigste", tekst: "Stoppekran, sikringsskap og installasjoner.", lenke: "/alt-om-boligen" }, { tittel: "3. Lagre rom", tekst: "Noter farger, gulv og materialer.", lenke: "/rom" }, { tittel: "4. Ta vare på papirene", tekst: "Last opp kvitteringer og garantier.", lenke: "/dokumentarkiv" }] : [{ tittel: "1. Registrer boligene", tekst: "Legg inn grunnlag og nøkkeltall.", lenke: "/boliger" }, { tittel: "2. Koble leietakere", tekst: "Samle leieforhold per bolig.", lenke: "/leietakere" }, { tittel: "3. Før betalingene", tekst: "Registrer faktiske inntekter og utgifter.", lenke: "/okonomi" }]; return <section className="border-b border-stone-200 bg-white px-4 py-10 sm:px-6"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold text-emerald-700">KORT VEIVISER</p><h2 className="mt-1 text-2xl font-bold">Kom raskt i gang</h2><div className={`mt-5 grid gap-3 ${privat ? "md:grid-cols-4" : "md:grid-cols-3"}`}>{steg.map((punkt) => <Link key={punkt.tittel} href={punkt.lenke} className="rounded-2xl border border-stone-200 p-4 hover:border-emerald-300 hover:bg-emerald-50"><strong>{punkt.tittel}</strong><span className="mt-1 block text-sm text-slate-500">{punkt.tekst}</span></Link>)}</div></div></section>; }
function Kort({tittel,tekst,lenke}:{tittel:string;tekst:string;lenke:string}) { return <article className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-stone-200"><h2 className="text-xl font-bold">{tittel}</h2><p className="mt-3 leading-7 text-slate-600">{tekst}</p><Link href={lenke} className="mt-6 inline-block font-bold text-emerald-700">Åpne →</Link></article>; }
function Omrade({merke,tittel,tekst,lenke}:{merke:string;tittel:string;tekst:string;lenke:string}) { return <article className="rounded-3xl border border-white/10 bg-white/5 p-8"><p className="text-xs font-bold tracking-wider text-emerald-300">{merke}</p><h2 className="mt-3 text-3xl font-bold">{tittel}</h2><p className="mt-3 text-slate-300">{tekst}</p><Link href={lenke} className="mt-7 inline-block rounded-xl bg-emerald-400 px-6 py-3 font-bold text-slate-950">Åpne</Link></article>; }
function Maalgruppe({merke,tittel,punkter}:{merke:string;tittel:string;punkter:string[]}) { const privat=merke==="PRIVAT BOLIG";return <article className="rounded-3xl bg-white p-8 shadow-sm ring-1 ring-stone-200"><p className="text-xs font-bold tracking-wider text-emerald-700">{merke}</p><h3 className="mt-3 text-2xl font-bold">{tittel}</h3><ul className="mt-6 space-y-3">{punkter.map(p=><li key={p} className="flex gap-3"><span className="font-bold text-emerald-600">✓</span>{p}</li>)}</ul><Link href={privat?"/mitt-hjem":"/oversikt"} className="mt-7 inline-block font-bold text-emerald-700">Se eksempel →</Link></article>; }
