"use client";

import { useEffect, useState } from "react";
import { lesAltOmBoligen, type Historikkinfo, type Skadeinfo } from "../lib/alt-om-boligen";
import { hentBoliger, oppdaterBolig, type BoligData } from "../lib/boliger";
import { lastOppDokument } from "../lib/dokumenter";

const tomSkade: Omit<Skadeinfo, "id" | "dokumentIder" | "bildeIder" | "lostDato" | "kostnad" | "losning"> = { tittel: "", omrade: "", type: "Fukt", oppdagetDato: new Date().toISOString().slice(0, 10), beskrivelse: "", status: "apen", handverkerId: "" };
const omrader = ["Kjøkken", "Bad", "Stue", "Soverom", "Kjeller", "Loft", "Tak", "Fasade", "Hage", "Garasje", "Annet"];
const typer = ["Fukt", "Lekkasje", "Sprekk", "Elektrisk", "Skadedyr", "Slitasje", "Knust/skadet", "Annet"];

export default function SkaderAvvik({ startApen = false, forvalgtBoligId = "" }: { startApen?: boolean; forvalgtBoligId?: string }) {
  const [boliger, setBoliger] = useState<BoligData[]>([]); const [boligId, setBoligId] = useState(""); const [aapen, setAapen] = useState(startApen); const [loser, setLoser] = useState<Skadeinfo | null>(null); const [skjema, setSkjema] = useState(tomSkade); const [bilder, setBilder] = useState<File[]>([]); const [filer, setFiler] = useState<File[]>([]); const [lostDato, setLostDato] = useState(new Date().toISOString().slice(0, 10)); const [kostnad, setKostnad] = useState(""); const [losning, setLosning] = useState(""); const [handverkerId, setHandverkerId] = useState(""); const [jobber, setJobber] = useState(false); const [feil, setFeil] = useState("");
  async function lastData() { try { const alle = (await hentBoliger()).filter((bolig) => String(bolig.brukstype || "") === "privat"); setBoliger(alle); setBoligId((gammel) => [forvalgtBoligId, gammel, String(alle[0]?.id || "")].find((id) => alle.some((bolig) => String(bolig.id) === id)) || ""); } catch { setFeil("Kunne ikke hente skader og avvik."); } }
  useEffect(() => { lastData(); }, []);
  const bolig = boliger.find((verdi) => String(verdi.id) === boligId) || boliger[0]; const data = bolig ? lesAltOmBoligen(bolig) : null; const skader = data?.skader || []; const kanRedigere = String(bolig?.tilgang || "eier") !== "leser";
  async function lastOppVedlegg(skadeId: string, dato: string) { const bildeIder: string[] = []; const dokumentIder: string[] = []; for (const fil of bilder) bildeIder.push(await lastOppDokument(fil, { boligId: String(bolig?.id || ""), navn: fil.name.replace(/\.[^.]+$/, ""), kategori: "skade", ar: Number(dato.slice(0, 4)), dokumentdato: dato, notat: `Tilhører skade: ${skadeId}` })); for (const fil of filer) dokumentIder.push(await lastOppDokument(fil, { boligId: String(bolig?.id || ""), navn: fil.name.replace(/\.[^.]+$/, ""), kategori: "skade", ar: Number(dato.slice(0, 4)), dokumentdato: dato, notat: `Tilhører skade: ${skadeId}` })); return { bildeIder, dokumentIder }; }
  async function lagre() { if (!bolig || !data || !skjema.tittel.trim()) { setFeil("Skriv hva som har skjedd."); return; } setJobber(true); setFeil(""); try { const id = crypto.randomUUID(); const vedlegg = await lastOppVedlegg(id, skjema.oppdagetDato); const skade: Skadeinfo = { id, ...skjema, tittel: skjema.tittel.trim(), dokumentIder: vedlegg.dokumentIder, bildeIder: vedlegg.bildeIder, lostDato: "", kostnad: 0, losning: "" }; await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...data, skader: [...data.skader, skade], oppdatert: new Date().toISOString() } }); setAapen(false); setSkjema(tomSkade); setBilder([]); setFiler([]); await lastData(); } catch { setFeil("Kunne ikke lagre skaden eller vedleggene."); } finally { setJobber(false); } }
  async function endreStatus(skade: Skadeinfo, status: Skadeinfo["status"]) { if (!bolig || !data) return; try { await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...data, skader: data.skader.map((verdi) => verdi.id === skade.id ? { ...verdi, status } : verdi), oppdatert: new Date().toISOString() } }); await lastData(); } catch { setFeil("Kunne ikke endre status."); } }
  function startLos(skade: Skadeinfo) { setLoser(skade); setLostDato(new Date().toISOString().slice(0, 10)); setKostnad(String(skade.kostnad || "")); setLosning(""); setHandverkerId(skade.handverkerId); setBilder([]); setFiler([]); }
  async function markerLost() { if (!bolig || !data || !loser || !losning.trim()) { setFeil("Skriv kort hva som ble gjort."); return; } setJobber(true); setFeil(""); try { const vedlegg = await lastOppVedlegg(loser.id, lostDato); const kontakt = data.kontakter.find((verdi) => verdi.id === handverkerId); const ferdigSkade: Skadeinfo = { ...loser, status: "lost", lostDato, kostnad: Number(kostnad) || 0, losning: losning.trim(), handverkerId, bildeIder: [...loser.bildeIder, ...vedlegg.bildeIder], dokumentIder: [...loser.dokumentIder, ...vedlegg.dokumentIder] }; const hendelse: Historikkinfo = { id: crypto.randomUUID(), dato: lostDato, tittel: `Reparert: ${loser.tittel}`, omrade: loser.omrade, kostnad: Number(kostnad) || 0, utfortAv: kontakt ? "firma" : "selv", firma: kontakt?.navn || "", handverkerId, beskrivelse: losning.trim(), dokumentIder: ferdigSkade.dokumentIder, bildeIder: ferdigSkade.bildeIder, kildeVedlikeholdId: "", kildeSkadeId: loser.id }; const finnes = data.historikk.some((verdi) => verdi.kildeSkadeId === loser.id); const historikk = finnes ? data.historikk.map((verdi) => verdi.kildeSkadeId === loser.id ? hendelse : verdi) : [...data.historikk, hendelse]; await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...data, skader: data.skader.map((verdi) => verdi.id === loser.id ? ferdigSkade : verdi), historikk, oppdatert: new Date().toISOString() } }); setLoser(null); setBilder([]); setFiler([]); await lastData(); } catch { setFeil("Kunne ikke fullføre saken eller lagre vedleggene."); } finally { setJobber(false); } }
  function kopier(skade: Skadeinfo) { const kontakt = data?.kontakter.find((verdi) => verdi.id === skade.handverkerId); navigator.clipboard.writeText([skade.tittel, `Bolig: ${String(bolig?.adresse || "")}`, `Område: ${skade.omrade}`, `Type: ${skade.type}`, `Oppdaget: ${skade.oppdagetDato}`, `Status: ${statusnavn(skade.status)}`, skade.beskrivelse, kontakt && `Kontakt: ${kontakt.navn} ${kontakt.telefon}`].filter(Boolean).join("\n")); }
  if (!bolig || !data) return <p className="rounded-2xl bg-white p-6 text-center text-slate-500">Ingen privat bolig er registrert.</p>;
  return <section><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><label className="text-sm font-semibold"><span className="mb-2 block">Bolig</span><select value={String(bolig.id)} onChange={(e) => setBoligId(e.target.value)} className="felt sm:w-80">{boliger.map((verdi) => <option key={verdi.id} value={verdi.id}>{String(verdi.adresse || "Privat bolig")}</option>)}</select></label>{kanRedigere && <button onClick={() => setAapen(true)} className="min-h-12 rounded-xl bg-red-500 px-5 py-3 font-bold text-white">+ Registrer skade/avvik</button>}</div>{!kanRedigere && <p className="mt-4 rounded-xl bg-stone-50 p-3 text-sm text-slate-600">Du har lesetilgang og kan derfor ikke endre saker.</p>}{feil && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{feil}</p>}<div className="mt-5 grid gap-4 lg:grid-cols-2">{skader.length ? skader.map((skade) => { const kontakt = data.kontakter.find((verdi) => verdi.id === skade.handverkerId); return <article key={skade.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-red-600">{skade.type} · {skade.omrade}</p><h3 className="mt-1 text-xl font-bold">{skade.tittel}</h3><p className="mt-1 text-sm text-slate-500">Oppdaget {formatDato(skade.oppdagetDato)}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusstil(skade.status)}`}>{statusnavn(skade.status)}</span></div>{skade.beskrivelse && <p className="mt-4 rounded-xl bg-stone-50 p-3 text-sm">{skade.beskrivelse}</p>}<p className="mt-3 text-sm text-slate-500">📸 {skade.bildeIder.length} bilder · 📄 {skade.dokumentIder.length} dokumenter{kontakt ? ` · ${kontakt.navn}` : ""}</p>{skade.status !== "lost" && <div className="mt-4 flex flex-wrap gap-3">{kanRedigere && <><select value={skade.status} onChange={(e) => endreStatus(skade, e.target.value as Skadeinfo["status"])} className="rounded-lg border px-3 py-2 text-sm"><option value="apen">Åpen</option><option value="kontaktet">Håndverker kontaktet</option><option value="under-arbeid">Under arbeid</option></select><button onClick={() => startLos(skade)} className="rounded-lg bg-emerald-500 px-4 py-2 text-sm font-bold text-white">Marker som løst</button></>}<button onClick={() => kopier(skade)} className="px-2 text-sm font-bold text-slate-600">Kopier til håndverker</button></div>}</article>; }) : <p className="rounded-2xl border border-dashed bg-white p-8 text-center text-slate-500 lg:col-span-2">Ingen skader eller avvik er registrert.</p>}</div>
    {aapen && <Modal tittel="Ny skade eller avvik" onLukk={() => setAapen(false)}><div className="grid gap-4 sm:grid-cols-2"><Felt label="Hva har skjedd? *"><input value={skjema.tittel} onChange={(e) => setSkjema({ ...skjema, tittel: e.target.value })} className="felt" /></Felt><Felt label="Område"><select value={skjema.omrade} onChange={(e) => setSkjema({ ...skjema, omrade: e.target.value })} className="felt"><option value="">Velg område</option>{omrader.map((verdi) => <option key={verdi}>{verdi}</option>)}</select></Felt><Felt label="Type"><select value={skjema.type} onChange={(e) => setSkjema({ ...skjema, type: e.target.value })} className="felt">{typer.map((verdi) => <option key={verdi}>{verdi}</option>)}</select></Felt><Felt label="Dato oppdaget"><input type="date" value={skjema.oppdagetDato} onChange={(e) => setSkjema({ ...skjema, oppdagetDato: e.target.value })} className="felt" /></Felt><Felt label="Håndverker (valgfritt)"><select value={skjema.handverkerId} onChange={(e) => setSkjema({ ...skjema, handverkerId: e.target.value })} className="felt"><option value="">Ikke valgt</option>{data.kontakter.map((verdi) => <option key={verdi.id} value={verdi.id}>{verdi.navn}</option>)}</select></Felt><label className="text-sm font-semibold sm:col-span-2">Beskrivelse<textarea rows={3} value={skjema.beskrivelse} onChange={(e) => setSkjema({ ...skjema, beskrivelse: e.target.value })} className="felt mt-2" /></label><Vedlegg bilder={bilder} filer={filer} setBilder={setBilder} setFiler={setFiler} /></div><Lagre onClick={lagre} jobber={jobber}>Lagre skade/avvik</Lagre></Modal>}
    {loser && <Modal tittel={`Løs: ${loser.tittel}`} onLukk={() => setLoser(null)}><div className="grid gap-4 sm:grid-cols-2"><Felt label="Når ble det løst?"><input type="date" value={lostDato} onChange={(e) => setLostDato(e.target.value)} className="felt" /></Felt><Felt label="Faktisk kostnad"><input inputMode="numeric" value={kostnad} onChange={(e) => setKostnad(e.target.value)} className="felt" /></Felt><Felt label="Hvem utførte arbeidet?"><select value={handverkerId} onChange={(e) => setHandverkerId(e.target.value)} className="felt"><option value="">Meg selv / ikke valgt</option>{data.kontakter.map((verdi) => <option key={verdi.id} value={verdi.id}>{verdi.navn}</option>)}</select></Felt><label className="text-sm font-semibold sm:col-span-2">Hva ble gjort? *<textarea rows={3} value={losning} onChange={(e) => setLosning(e.target.value)} className="felt mt-2" /></label><Vedlegg bilder={bilder} filer={filer} setBilder={setBilder} setFiler={setFiler} /></div><Lagre onClick={markerLost} jobber={jobber}>Marker som løst og lagre i historikken</Lagre></Modal>}
  </section>;
}

function Vedlegg({ bilder, filer, setBilder, setFiler }: { bilder: File[]; filer: File[]; setBilder: (filer: File[]) => void; setFiler: (filer: File[]) => void }) { return <><Felt label={`Ta bilde${bilder.length ? ` (${bilder.length} valgt)` : ""}`}><input type="file" accept="image/*" capture="environment" onChange={(e) => setBilder([...bilder, ...Array.from(e.target.files || [])])} className="felt text-sm" /></Felt><Felt label="Last opp bilder"><input type="file" multiple accept="image/*,.heic,.heif" onChange={(e) => setBilder([...bilder, ...Array.from(e.target.files || [])])} className="felt text-sm" /></Felt><Felt label={`Dokumenter${filer.length ? ` (${filer.length})` : ""}`}><input type="file" multiple accept="image/*,.pdf,.doc,.docx" onChange={(e) => setFiler(Array.from(e.target.files || []))} className="felt text-sm" /></Felt></>; }
function Modal({ tittel, onLukk, children }: { tittel: string; onLukk: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-3"><div className="mx-auto my-4 max-w-2xl rounded-3xl bg-white p-5 sm:my-10 sm:p-7"><div className="mb-6 flex justify-between gap-4"><h2 className="text-2xl font-bold">{tittel}</h2><button onClick={onLukk} className="font-semibold text-slate-500">Lukk</button></div>{children}</div></div>; }
function Felt({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-semibold"><span className="mb-2 block">{label}</span>{children}</label>; }
function Lagre({ onClick, jobber, children }: { onClick: () => void; jobber: boolean; children: React.ReactNode }) { return <button onClick={onClick} disabled={jobber} className="mt-6 min-h-12 w-full rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white disabled:opacity-50">{jobber ? "Lagrer…" : children}</button>; }
function statusnavn(status: Skadeinfo["status"]) { return { apen: "Åpen", kontaktet: "Håndverker kontaktet", "under-arbeid": "Under arbeid", lost: "Løst" }[status]; }
function statusstil(status: Skadeinfo["status"]) { return { apen: "bg-red-100 text-red-700", kontaktet: "bg-amber-100 text-amber-800", "under-arbeid": "bg-blue-100 text-blue-700", lost: "bg-emerald-100 text-emerald-700" }[status]; }
function formatDato(dato: string) { return dato ? new Intl.DateTimeFormat("nb-NO").format(new Date(`${dato}T12:00:00`)) : "ukjent dato"; }
