"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Navigasjon from "../components/Navigasjon";
import { hentBoliger, type BoligData } from "../lib/boliger";
import { dokumentLenke, hentDokumenter, lastOppDokument, slettDokument, type Dokument } from "../lib/dokumenter";
import { bilagLenke, hentOkonomiposter } from "../lib/okonomi";
import { createClient } from "../lib/supabase/client";

const kategorier = [["kvittering","Kvittering"],["faktura","Faktura"],["bankarsoppgave","Bankens årsoppgave"],["forsikring","Forsikringsdokument"],["vedlikehold","Vedlikehold / bilder"],["takst","Takst"],["meglervurdering","Meglerverdivurdering"],["kontrakt","Kontrakt"],["annet","Annet"]] as const;
const aarNaa = new Date().getFullYear();

export default function Dokumentarkiv() {
  const [dokumenter, setDokumenter] = useState<Dokument[]>([]); const [boliger, setBoliger] = useState<BoligData[]>([]); const [innlogget, setInnlogget] = useState(false); const [laster, setLaster] = useState(true); const [jobber, setJobber] = useState(false); const [feil, setFeil] = useState("");
  const [sok, setSok] = useState(""); const [boligfilter, setBoligfilter] = useState("alle"); const [kategorifilter, setKategorifilter] = useState("alle"); const [aarfilter, setAarfilter] = useState("alle"); const [visSkjema, setVisSkjema] = useState(false);
  const [fil, setFil] = useState<File | null>(null); const [navn, setNavn] = useState(""); const [boligId, setBoligId] = useState(""); const [kategori, setKategori] = useState("kvittering"); const [aar, setAar] = useState(aarNaa); const [dato, setDato] = useState(() => new Date().toISOString().slice(0,10)); const [notat, setNotat] = useState("");

  async function lastData() { setLaster(true); setFeil(""); try { const supabase = createClient(); const { data } = await supabase.auth.getUser(); const erInnlogget = Boolean(data.user); setInnlogget(erInnlogget); const [b, d] = await Promise.all([hentBoliger(), hentDokumenter()]); const bilagsaar = Array.from({ length: 7 }, (_, i) => aarNaa + 1 - i); const poster = erInnlogget ? (await Promise.all(bilagsaar.map(hentOkonomiposter))).flat() : [];
      const bilag: Dokument[] = poster.filter((p) => p.bilagSti).map((p) => ({ id: `okonomi-${p.id}`, boligId: p.boligId, navn: p.beskrivelse || kategorinavn(p.kategori), kategori: p.kategori === "vedlikehold" ? "vedlikehold" : p.bilagFilnavn.toLowerCase().includes("faktura") ? "faktura" : "kvittering", ar: Number(p.dato.slice(0,4)), dokumentdato: p.dato, notat: "Bilag fra Økonomi", filsti: p.bilagSti, filnavn: p.bilagFilnavn, filtype: "", filstorrelse: 0, createdAt: p.dato, kilde: "okonomi" })); setBoliger(b); setDokumenter([...d, ...bilag]); setBoligId((g) => g || b[0]?.id || "");
    } catch (e) { console.error(e); setFeil("Kunne ikke hente dokumentene. Kontroller at SQL-oppsettet er kjørt."); } finally { setLaster(false); } }
  useEffect(() => { lastData(); }, []);
  const aarvalg = useMemo(() => [...new Set([aarNaa, ...dokumenter.map((d) => d.ar)])].sort((a,b) => b-a), [dokumenter]);
  const viste = useMemo(() => { const t = sok.trim().toLowerCase(); return dokumenter.filter((d) => (!t || `${d.navn} ${d.filnavn} ${d.notat}`.toLowerCase().includes(t)) && (boligfilter === "alle" || d.boligId === boligfilter) && (kategorifilter === "alle" || d.kategori === kategorifilter) && (aarfilter === "alle" || d.ar === Number(aarfilter))).sort((a,b) => (b.dokumentdato || b.createdAt).localeCompare(a.dokumentdato || a.createdAt)); }, [dokumenter,sok,boligfilter,kategorifilter,aarfilter]);
  async function lagre(e: FormEvent) { e.preventDefault(); if (!innlogget) { window.location.assign("/logg-inn"); return; } if (!fil) { setFeil("Velg en fil."); return; } setJobber(true); setFeil(""); try { await lastOppDokument(fil,{ boligId, navn: navn || fil.name, kategori, ar: aar, dokumentdato: dato, notat }); setVisSkjema(false); setFil(null); setNavn(""); setNotat(""); await lastData(); } catch (e) { const kode=e instanceof Error?e.message:""; setFeil(kode==="FIL_FOR_STOR"?"Filen kan ikke være større enn 25 MB.":kode==="UGYLDIG_FILTYPE"?"Bruk PDF, bilde, Word eller Excel.":"Kunne ikke laste opp dokumentet."); } finally { setJobber(false); } }
  async function aapne(d: Dokument) { if (!d.filsti) { if (!innlogget) window.location.assign("/logg-inn"); return; } const vindu=window.open("","_blank"); try { const url=d.kilde==="okonomi"?await bilagLenke(d.filsti):await dokumentLenke(d.filsti); if(vindu) vindu.location.href=url; } catch { vindu?.close(); setFeil("Kunne ikke åpne dokumentet."); } }
  async function slett(d: Dokument) { if (d.kilde==="okonomi") { setFeil("Dette bilaget slettes eller endres under Økonomi."); return; } if(!confirm(`Slett «${d.navn}»?`)) return; try { await slettDokument(d); setDokumenter((gamle)=>gamle.filter((v)=>v.id!==d.id)); } catch { setFeil("Kunne ikke slette dokumentet."); } }

  return <main className="min-h-screen bg-slate-100 text-slate-900"><Navigasjon/><header className="bg-slate-950 px-4 py-10 text-white sm:px-6"><div className="mx-auto max-w-7xl"><p className="font-semibold text-emerald-400">ALT PÅ ETT STED</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Dokumentarkiv</h1><p className="mt-3 max-w-3xl text-slate-300">Finn kvitteringer, fakturaer, årsoppgaver, forsikring, bilder, takster og andre dokumenter.</p></div></header>
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><section className="grid gap-3 rounded-2xl bg-white p-5 shadow-sm md:grid-cols-2 xl:grid-cols-[1fr_220px_210px_140px_auto]"><input value={sok} onChange={(e)=>setSok(e.target.value)} placeholder="Søk i navn, fil eller notat" className="rounded-xl border px-4 py-3"/><select value={boligfilter} onChange={(e)=>setBoligfilter(e.target.value)} className="rounded-xl border px-3 py-3"><option value="alle">Alle boliger</option>{boliger.map((b)=><option key={b.id} value={b.id}>{String(b.adresse||"Uten adresse")}</option>)}</select><select value={kategorifilter} onChange={(e)=>setKategorifilter(e.target.value)} className="rounded-xl border px-3 py-3"><option value="alle">Alle kategorier</option>{kategorier.map((k)=><option key={k[0]} value={k[0]}>{k[1]}</option>)}</select><select value={aarfilter} onChange={(e)=>setAarfilter(e.target.value)} className="rounded-xl border px-3 py-3"><option value="alle">Alle år</option>{aarvalg.map((a)=><option key={a}>{a}</option>)}</select><button onClick={()=>setVisSkjema(true)} className="rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white">+ Last opp</button></section>
    {feil&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{feil}</p>}
    <div className="mt-5 flex items-center justify-between"><p className="text-sm text-slate-500">{viste.length} {viste.length===1?"dokument":"dokumenter"}</p><p className="text-xs text-slate-500">Bilag fra Økonomi vises automatisk</p></div>
    <section className="mt-3 overflow-hidden rounded-2xl bg-white shadow-sm">{laster?<p className="p-12 text-center text-slate-500">Laster…</p>:viste.length===0?<div className="p-12 text-center"><h2 className="text-xl font-bold">Ingen dokumenter funnet</h2><p className="mt-2 text-slate-500">Last opp det første dokumentet eller endre filtrene.</p></div>:<div className="divide-y">{viste.map((d)=><article key={d.id} className="grid gap-4 p-5 md:grid-cols-[100px_1fr_auto] md:items-center"><div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-100 text-xs font-bold uppercase text-slate-500">{(d.filnavn.split(".").pop()||"fil").slice(0,4)}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{d.navn}</h2><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-semibold text-emerald-800">{kategorinavn(d.kategori)}</span>{d.kilde==="okonomi"&&<span className="rounded-full bg-blue-100 px-2 py-1 text-xs font-semibold text-blue-800">Fra Økonomi</span>}</div><p className="mt-1 text-sm text-slate-500">{adresse(boliger,d.boligId)} · {d.ar}{d.dokumentdato?` · ${formatDato(d.dokumentdato)}`:""}</p><p className="mt-1 text-sm text-slate-500">{d.filnavn}{d.notat?` · ${d.notat}`:""}</p></div><div className="flex gap-3 md:justify-end"><button onClick={()=>aapne(d)} className="font-semibold text-emerald-700">Åpne</button><button onClick={()=>slett(d)} className="font-semibold text-red-600">Slett</button></div></article>)}</div>}</section></div>
    {visSkjema&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={lagre} className="mx-auto mt-8 max-w-2xl rounded-3xl bg-white p-6 sm:mt-16 sm:p-8"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Last opp dokument</h2><p className="mt-1 text-sm text-slate-500">PDF, bilde, Word eller Excel · maks 25 MB</p></div><button type="button" onClick={()=>setVisSkjema(false)}>Lukk</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Felt label="Fil"><input required type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx" onChange={(e)=>{const f=e.target.files?.[0]||null;setFil(f);if(f&&!navn)setNavn(f.name.replace(/\.[^.]+$/, ""));}} className="w-full rounded-xl border p-3 text-sm"/></Felt><Felt label="Navn"><input value={navn} onChange={(e)=>setNavn(e.target.value)} className="w-full rounded-xl border px-4 py-3"/></Felt><Felt label="Bolig"><select value={boligId} onChange={(e)=>setBoligId(e.target.value)} className="w-full rounded-xl border px-4 py-3"><option value="">Ikke koblet til bolig</option>{boliger.map((b)=><option key={b.id} value={b.id}>{String(b.adresse||"Uten adresse")}</option>)}</select></Felt><Felt label="Kategori"><select value={kategori} onChange={(e)=>setKategori(e.target.value)} className="w-full rounded-xl border px-4 py-3">{kategorier.map((k)=><option key={k[0]} value={k[0]}>{k[1]}</option>)}</select></Felt><Felt label="År"><input type="number" min="1900" max="2200" value={aar} onChange={(e)=>setAar(Number(e.target.value))} className="w-full rounded-xl border px-4 py-3"/></Felt><Felt label="Dokumentdato"><input type="date" value={dato} onChange={(e)=>setDato(e.target.value)} className="w-full rounded-xl border px-4 py-3"/></Felt><label className="sm:col-span-2 text-sm font-semibold">Notat<textarea rows={3} value={notat} onChange={(e)=>setNotat(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label></div><button disabled={jobber} className="mt-6 w-full rounded-xl bg-emerald-500 px-6 py-3 font-bold text-white disabled:opacity-50">{jobber?"Laster opp…":"Lagre dokument"}</button></form></div>}
  </main>;
}
function Felt({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-semibold"><span className="mb-2 block">{label}</span>{children}</label>}
function kategorinavn(v:string){return kategorier.find((k)=>k[0]===v)?.[1]||v.replaceAll("_"," ")}
function adresse(b:BoligData[],id:string){return String(b.find((v)=>v.id===id)?.adresse||"Ikke koblet til bolig")}
function formatDato(v:string){return new Intl.DateTimeFormat("nb-NO").format(new Date(`${v}T12:00:00`))}
