"use client";

import { useEffect, useMemo, useState } from "react";
import Navigasjon from "../components/Navigasjon";
import { demoAltOmBoligen, lesAltOmBoligen, type Forsikringinfo } from "../lib/alt-om-boligen";
import { hentBoliger, oppdaterBolig, type BoligData } from "../lib/boliger";
import { dokumentLenke, hentDokumenter, lastOppDokument, type Dokument } from "../lib/dokumenter";
import { createClient } from "../lib/supabase/client";

type Skjema = Omit<Forsikringinfo, "id" | "dokumentId">;
const tomt: Skjema = { type: "Husforsikring", selskap: "", avtalenummer: "", arspris: "", egenandel: "", gyldigFra: "", fornyes: "", kontakt: "", notat: "" };
const demoGrunnlag: BoligData = { id: "demo-privat-hjem", brukstype: "privat", adresse: "Eksempelveien 12, Bergen", boligtype: "Enebolig", byggeaar: "1958", areal: 142 };
const demoBolig: BoligData = { ...demoGrunnlag, altOmBoligen: demoAltOmBoligen(demoGrunnlag) };

export default function ForsikringerSide() {
  const [boliger, setBoliger] = useState<BoligData[]>([]); const [dokumenter, setDokumenter] = useState<Dokument[]>([]); const [innlogget, setInnlogget] = useState(false); const [laster, setLaster] = useState(true); const [feil, setFeil] = useState(""); const [aapen, setAapen] = useState(false); const [jobber, setJobber] = useState(false);
  const [boligId, setBoligId] = useState(""); const [redigererId, setRedigererId] = useState(""); const [skjema, setSkjema] = useState<Skjema>(tomt); const [fil, setFil] = useState<File | null>(null);
  async function lastData() { setLaster(true); setFeil(""); try { const { data } = await createClient().auth.getUser(); const erInnlogget = Boolean(data.user); setInnlogget(erInnlogget); if (!erInnlogget) { setBoliger([demoBolig]); setDokumenter([]); return; } const [alle, filer] = await Promise.all([hentBoliger(), hentDokumenter()]); setBoliger(alle.filter((bolig) => String(bolig.brukstype || "") === "privat")); setDokumenter(filer.filter((dokument) => dokument.kilde === "arkiv")); } catch { setFeil("Kunne ikke hente forsikringene."); } finally { setLaster(false); } }
  useEffect(() => { lastData(); }, []);
  const forsikringer = useMemo(() => boliger.flatMap((bolig) => lesAltOmBoligen(bolig).forsikringer.map((forsikring) => ({ forsikring, bolig }))).sort((a, b) => a.forsikring.fornyes.localeCompare(b.forsikring.fornyes)), [boliger]);
  function ny() { if (!innlogget) { window.location.assign("/logg-inn"); return; } setBoligId(String(boliger[0]?.id || "")); setRedigererId(""); setSkjema(tomt); setFil(null); setAapen(true); }
  function rediger(forsikring: Forsikringinfo, bolig: BoligData) { if (!innlogget) { window.location.assign("/logg-inn"); return; } const { id: _id, dokumentId: _dokumentId, ...verdier } = forsikring; setBoligId(String(bolig.id)); setRedigererId(forsikring.id); setSkjema(verdier); setFil(null); setAapen(true); }
  async function lagre(event: React.FormEvent) { event.preventDefault(); const bolig = boliger.find((verdi) => String(verdi.id) === boligId); if (!bolig || !skjema.type.trim()) return; setJobber(true); setFeil(""); try { const alt = lesAltOmBoligen(bolig); const gammel = alt.forsikringer.find((verdi) => verdi.id === redigererId); let dokumentId = gammel?.dokumentId || ""; if (fil) dokumentId = await lastOppDokument(fil, { boligId, navn: `Forsikringsbevis – ${skjema.type}`, kategori: "forsikring", ar: Number((skjema.gyldigFra || new Date().toISOString()).slice(0, 4)), dokumentdato: skjema.gyldigFra || new Date().toISOString().slice(0, 10), notat: `${skjema.selskap}${skjema.avtalenummer ? ` · ${skjema.avtalenummer}` : ""}` }); const forsikring: Forsikringinfo = { id: gammel?.id || crypto.randomUUID(), dokumentId, ...skjema, type: skjema.type.trim() }; const liste = gammel ? alt.forsikringer.map((verdi) => verdi.id === gammel.id ? forsikring : verdi) : [...alt.forsikringer, forsikring]; await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...alt, forsikringer: liste, oppdatert: new Date().toISOString() } }); setAapen(false); await lastData(); } catch { setFeil("Kunne ikke lagre forsikringen eller dokumentet."); } finally { setJobber(false); } }
  async function slett(forsikring: Forsikringinfo, bolig: BoligData) { if (!confirm(`Slett «${forsikring.type}»? Forsikringsbeviset beholdes i dokumentarkivet.`)) return; setJobber(true); try { const alt = lesAltOmBoligen(bolig); await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...alt, forsikringer: alt.forsikringer.filter((verdi) => verdi.id !== forsikring.id), oppdatert: new Date().toISOString() } }); await lastData(); } catch { setFeil("Kunne ikke slette forsikringen."); } finally { setJobber(false); } }
  async function aapneDokument(id: string) { const dokument = dokumenter.find((verdi) => verdi.id === id); if (!dokument) return; const vindu = window.open("", "_blank"); try { const url = await dokumentLenke(dokument.filsti); if (vindu) vindu.location.href = url; } catch { vindu?.close(); setFeil("Kunne ikke åpne forsikringsbeviset."); } }
  return <main className="min-h-screen bg-stone-50 text-slate-900"><Navigasjon /><header className="bg-gradient-to-br from-sky-100 via-stone-100 to-emerald-100 px-4 py-12 sm:px-6"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold tracking-wider text-sky-800">DOKUMENTER</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-bold">Forsikringer</h1><p className="mt-3 max-w-2xl text-slate-600">Samle selskap, avtalenummer, pris, egenandel, fornyelse og forsikringsbevis.</p></div><button onClick={ny} className="min-h-12 rounded-xl bg-sky-600 px-5 py-3 font-bold text-white">+ Legg til forsikring</button></div></div></header>
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">{feil && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{feil}</p>}{laster ? <p className="py-16 text-center text-slate-500">Laster forsikringer…</p> : !boliger.length ? <section className="rounded-3xl bg-white p-10 text-center"><h2 className="text-2xl font-bold">Ingen privat bolig</h2><p className="mt-2 text-slate-500">Opprett en privat bolig under Mitt hjem først.</p></section> : <div className="grid gap-4 lg:grid-cols-2">{forsikringer.length ? forsikringer.map(({ forsikring, bolig }) => <article key={forsikring.id} className="rounded-3xl bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-sky-700">{forsikring.selskap || "Selskap ikke registrert"}</p><h2 className="mt-1 text-xl font-bold">{forsikring.type}</h2><p className="mt-1 text-sm text-slate-500">{String(bolig.adresse || "Privat bolig")}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${forsikringstatus(forsikring.fornyes).stil}`}>{forsikringstatus(forsikring.fornyes).tekst}</span></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info navn="Fornyes" verdi={formatDato(forsikring.fornyes)} /><Info navn="Årspris" verdi={forsikring.arspris ? `${forsikring.arspris} kr` : "Ikke registrert"} /><Info navn="Egenandel" verdi={forsikring.egenandel ? `${forsikring.egenandel} kr` : "Ikke registrert"} /><Info navn="Avtalenummer" verdi={forsikring.avtalenummer || "Ikke registrert"} /></dl>{forsikring.notat && <p className="mt-4 rounded-xl bg-stone-50 p-3 text-sm text-slate-600">{forsikring.notat}</p>}<div className="mt-5 flex flex-wrap gap-4 text-sm font-bold"><button onClick={() => rediger(forsikring, bolig)} className="text-emerald-700">Rediger</button>{forsikring.dokumentId && <button onClick={() => aapneDokument(forsikring.dokumentId)} className="text-sky-700">Se forsikringsbevis</button>}{innlogget && <button disabled={jobber} onClick={() => slett(forsikring, bolig)} className="text-red-600">Slett</button>}</div></article>) : <p className="rounded-3xl border border-dashed border-stone-300 bg-white p-8 text-center text-slate-500 lg:col-span-2">Ingen forsikringer er registrert ennå.</p>}</div>}</div>
    {aapen && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-3"><form onSubmit={lagre} className="mx-auto my-5 max-w-2xl rounded-3xl bg-white p-5 sm:my-10 sm:p-7"><div className="flex justify-between gap-4"><div><h2 className="text-2xl font-bold">{redigererId ? "Rediger forsikring" : "Ny forsikring"}</h2><p className="mt-1 text-sm text-slate-500">Fyll bare inn det du ønsker å ha oversikt over.</p></div><button type="button" onClick={() => setAapen(false)} className="font-semibold text-slate-500">Lukk</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Felt label="Bolig"><select value={boligId} onChange={(e) => setBoligId(e.target.value)} className="felt">{boliger.map((bolig) => <option key={bolig.id} value={bolig.id}>{String(bolig.adresse || "Privat bolig")}</option>)}</select></Felt><Felt label="Type forsikring *"><input required value={skjema.type} onChange={(e) => setSkjema({ ...skjema, type: e.target.value })} className="felt" /></Felt><Felt label="Forsikringsselskap"><input value={skjema.selskap} onChange={(e) => setSkjema({ ...skjema, selskap: e.target.value })} className="felt" /></Felt><Felt label="Avtalenummer"><input value={skjema.avtalenummer} onChange={(e) => setSkjema({ ...skjema, avtalenummer: e.target.value })} className="felt" /></Felt><Felt label="Årspris"><input inputMode="numeric" value={skjema.arspris} onChange={(e) => setSkjema({ ...skjema, arspris: e.target.value })} className="felt" /></Felt><Felt label="Egenandel"><input inputMode="numeric" value={skjema.egenandel} onChange={(e) => setSkjema({ ...skjema, egenandel: e.target.value })} className="felt" /></Felt><Felt label="Gyldig fra"><input type="date" value={skjema.gyldigFra} onChange={(e) => setSkjema({ ...skjema, gyldigFra: e.target.value })} className="felt" /></Felt><Felt label="Fornyes / utløper"><input type="date" value={skjema.fornyes} onChange={(e) => setSkjema({ ...skjema, fornyes: e.target.value })} className="felt" /></Felt><Felt label="Kontakt"><input value={skjema.kontakt} onChange={(e) => setSkjema({ ...skjema, kontakt: e.target.value })} placeholder="Telefon eller e-post" className="felt" /></Felt><Felt label={redigererId ? "Nytt forsikringsbevis" : "Forsikringsbevis"}><input type="file" accept="image/*,.pdf,.doc,.docx" onChange={(e) => setFil(e.target.files?.[0] || null)} className="felt text-sm" /></Felt><label className="text-sm font-semibold sm:col-span-2">Notat<textarea rows={3} value={skjema.notat} onChange={(e) => setSkjema({ ...skjema, notat: e.target.value })} className="felt mt-2" /></label></div><button disabled={jobber} className="mt-6 min-h-12 w-full rounded-xl bg-sky-600 px-6 py-3 font-bold text-white disabled:opacity-50">{jobber ? "Lagrer…" : "Lagre forsikring"}</button></form></div>}
  </main>;
}

function Felt({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-semibold"><span className="mb-2 block">{label}</span>{children}</label>; }
function Info({ navn, verdi }: { navn: string; verdi: string }) { return <div className="rounded-xl bg-stone-50 p-3"><dt className="text-xs font-bold uppercase text-slate-400">{navn}</dt><dd className="mt-1 break-words font-semibold">{verdi}</dd></div>; }
function formatDato(verdi: string) { return verdi ? new Intl.DateTimeFormat("nb-NO").format(new Date(`${verdi}T12:00:00`)) : "Ikke registrert"; }
function forsikringstatus(fornyes: string) { if (!fornyes) return { tekst: "Aktiv", stil: "bg-emerald-100 text-emerald-800" }; const dager = Math.ceil((new Date(`${fornyes}T12:00:00`).getTime() - Date.now()) / 86400000); if (dager < 0) return { tekst: "Må kontrolleres", stil: "bg-red-100 text-red-800" }; if (dager <= 60) return { tekst: "Fornyes snart", stil: "bg-amber-100 text-amber-900" }; return { tekst: "Aktiv", stil: "bg-emerald-100 text-emerald-800" }; }
