import Link from "next/link";
import Navigasjon from "./components/Navigasjon";
import ForsidePortefolje from "./components/ForsidePortefolje";

export default function Home() {
  return <main className="min-h-screen bg-white text-slate-900"><Navigasjon />
    <section className="overflow-hidden bg-slate-950 px-4 py-20 text-white sm:px-6 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><p className="font-semibold text-emerald-400">LAGET FOR NORSKE UTLEIERE</p><h1 className="mt-4 max-w-3xl text-4xl font-bold leading-tight sm:text-6xl">Full kontroll på utleien – på ett sted</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Samle boliger, leietakere, husleie, kontrakter, vedlikehold og dokumentasjon. Eiendomsoversikten gjør det enklere å følge opp hele utleieporteføljen.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/logg-inn" className="rounded-xl bg-emerald-400 px-6 py-3 text-center font-bold text-slate-950 hover:bg-emerald-300">Kom i gang gratis</Link><Link href="/oversikt" className="rounded-xl border border-slate-600 px-6 py-3 text-center font-semibold hover:bg-slate-900">Se eksempeloversikt</Link></div><p className="mt-4 text-sm text-slate-400">Gratis i testperioden · Ingen binding</p></div>
      <ForsidePortefolje />
    </div></section>
    <section className="px-4 py-16 sm:px-6 sm:py-24"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="font-semibold text-emerald-700">DET VIKTIGSTE SAMLET</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Mindre leting. Bedre oversikt.</h2><p className="mt-4 text-lg leading-8 text-slate-600">I stedet for regneark, mapper og løse påminnelser får du én arbeidsflate for den daglige utleien.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
      <Funksjon tittel="Boliger og nøkkeltall" tekst="Se verdi, lån, bruttoyield, kontantstrøm og egenkapital per bolig og samlet." href="/boliger" merke="EIENDOM"/><Funksjon tittel="Leietakere og leieforhold" tekst="Koble hver leietaker til riktig bolig og følg leie, kontraktsperiode og status." href="/leietakere" merke="EIENDOM"/><Funksjon tittel="Faktisk økonomi" tekst="Registrer mottatt husleie og utgifter, og marker alle synlige betalinger samtidig." href="/okonomi" merke="ØKONOMI"/><Funksjon tittel="Årsrapport" tekst="Få et ryddig underlag med inntekter, kostnader, renter og poster som må vurderes." href="/skatterapport" merke="ØKONOMI"/><Funksjon tittel="Vedlikehold og kalender" tekst="Samle oppgaver, visninger og møter, og se hva som skjer den kommende uken." href="/kalender" merke="PLANLEGGING"/><Funksjon tittel="Dokumenter og kontrakter" tekst="Oppbevar bilag og viktige eiendomsdokumenter privat, sortert på bolig og år." href="/dokumentarkiv" merke="DOKUMENTER"/>
    </div></div></section>
    <section className="bg-slate-100 px-4 py-16 sm:px-6 sm:py-24"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="font-semibold text-emerald-700">SLIK FUNGERER DET</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Kom i gang på noen få steg</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><Steg nr="1" tittel="Registrer boligene" tekst="Legg inn adresse, kjøpesum, lån, leie og kostnader."/><Steg nr="2" tittel="Koble til leietakere" tekst="Velg bolig, kontraktsperiode og månedlig husleie."/><Steg nr="3" tittel="Følg opp gjennom året" tekst="Bekreft betalinger, lagre bilag og få automatisk årsoversikt."/></div></div></section>
    <section className="bg-emerald-500 px-4 py-16 text-slate-950 sm:px-6"><div className="mx-auto flex max-w-5xl flex-col items-center justify-between gap-7 text-center lg:flex-row lg:text-left"><div><h2 className="text-3xl font-bold">Prøv Eiendomsoversikten gratis</h2><p className="mt-3 text-lg text-emerald-950">Vi er i testfasen og ønsker ærlige tilbakemeldinger fra utleiere.</p></div><Link href="/logg-inn" className="shrink-0 rounded-xl bg-slate-950 px-7 py-3.5 font-bold text-white hover:bg-slate-800">Opprett gratis konto</Link></div></section>
  </main>;
}

function Funksjon({tittel,tekst,href,merke}:{tittel:string;tekst:string;href:string;merke:string}) { return <Link href={href} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-emerald-300 hover:shadow-lg"><p className="text-xs font-bold tracking-wider text-emerald-700">{merke}</p><h3 className="mt-3 text-xl font-bold group-hover:text-emerald-700">{tittel}</h3><p className="mt-3 leading-7 text-slate-600">{tekst}</p><p className="mt-5 font-semibold text-emerald-700">Se funksjonen →</p></Link>; }
function Steg({nr,tittel,tekst}:{nr:string;tittel:string;tekst:string}) { return <div className="rounded-2xl bg-white p-7 shadow-sm"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-100 text-lg font-bold text-emerald-800">{nr}</span><h3 className="mt-5 text-xl font-bold">{tittel}</h3><p className="mt-3 leading-7 text-slate-600">{tekst}</p></div>; }
