"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Navigasjon from "../components/Navigasjon";
import { demoAltOmBoligen, lesAltOmBoligen, type Historikkinfo, type Rominfo } from "../lib/alt-om-boligen";
import { hentBoliger, oppdaterBolig, type BoligData } from "../lib/boliger";
import { dokumentLenker, hentDokumenter, lastOppDokument, type Dokument } from "../lib/dokumenter";
import { createClient } from "../lib/supabase/client";

const demoGrunnlag: BoligData = { id: "demo-privat-hjem", brukstype: "privat", adresse: "Eksempelveien 12, Bergen", boligtype: "Enebolig", byggeaar: "1958", areal: 142 };
const demoBolig: BoligData = { ...demoGrunnlag, altOmBoligen: demoAltOmBoligen(demoGrunnlag) };
const tomtRom: Rominfo = { id: "", navn: "", areal: "", veggfarge: "", fargekode: "", maling: "", glans: "", gulv: "", tak: "", lister: "", sistPusset: "", notat: "", bildeIder: [] };

export default function RomSide() {
  const [boliger, setBoliger] = useState<BoligData[]>([]); const [boligId, setBoligId] = useState(""); const [innlogget, setInnlogget] = useState(false); const [laster, setLaster] = useState(true); const [feil, setFeil] = useState("");
  const [valgt, setValgt] = useState<Rominfo | null>(null); const [redigerer, setRedigerer] = useState(false); const [utkast, setUtkast] = useState<Rominfo>(tomtRom); const [jobber, setJobber] = useState(false); const [sok, setSok] = useState("");
  const [dokumenter, setDokumenter] = useState<Dokument[]>([]); const [bildelenker, setBildelenker] = useState<Record<string, string>>({}); const [nyeBilder, setNyeBilder] = useState<File[]>([]);
  const automatiskFordelt = useRef(new Set<string>());
  async function lastData() { setLaster(true); setFeil(""); try { const { data } = await createClient().auth.getUser(); const erInnlogget = Boolean(data.user); setInnlogget(erInnlogget); const [alle, filer] = await Promise.all([erInnlogget ? hentBoliger() : Promise.resolve([demoBolig]), erInnlogget ? hentDokumenter() : Promise.resolve([])]); const privateBoliger = alle.filter((bolig) => String(bolig.brukstype || "") === "privat"); setBoliger(privateBoliger); setDokumenter(filer); setBoligId((gammel) => privateBoliger.some((bolig) => bolig.id === gammel) ? gammel : String(privateBoliger[0]?.id || "")); } catch { setFeil("Kunne ikke hente rommene."); } finally { setLaster(false); } }
  useEffect(() => { lastData(); }, []);
  const bolig = boliger.find((verdi) => String(verdi.id) === boligId) || boliger[0]; const data = bolig ? lesAltOmBoligen(bolig) : null;
  const kanRedigere = String(bolig?.tilgang || "eier") !== "leser";
  const boligbilder = useMemo(() => dokumenter.filter((dokument) => dokument.boligId === String(bolig?.id || "") && (dokument.filtype.startsWith("image/") || dokument.kategori === "boligbilde")).sort((a, b) => finnBildenummer(a) - finnBildenummer(b)), [dokumenter, bolig?.id]);
  const rom = useMemo(() => (data?.rom || []).filter((verdi) => `${verdi.navn} ${verdi.veggfarge} ${verdi.fargekode} ${verdi.gulv}`.toLowerCase().includes(sok.toLowerCase())), [data, sok]);
  const historikkFor = (rommet: Rominfo): Historikkinfo[] => (data?.historikk || []).filter((hendelse) => hendelse.romId === rommet.id || (!hendelse.romId && hendelse.omrade.trim().toLowerCase() === rommet.navn.trim().toLowerCase())).sort((a, b) => b.dato.localeCompare(a.dato));
  const bilderFor = (rommet: Rominfo) => dokumenter.filter((dokument) => (rommet.bildeIder || []).includes(dokument.id) && dokument.filtype.startsWith("image/"));
  useEffect(() => {
    let aktiv = true;
    const aktuelle = boligbilder.filter((dokument) => dokument.filsti && !bildelenker[dokument.id]);
    if (!aktuelle.length) return () => { aktiv = false; };
    dokumentLenker(aktuelle.map((dokument) => dokument.filsti)).then((lenker) => {
      if (!aktiv) return;
      const verdier = aktuelle.flatMap((dokument) => lenker[dokument.filsti] ? [[dokument.id, lenker[dokument.filsti]] as const] : []);
      if (verdier.length) setBildelenker((gamle) => ({ ...gamle, ...Object.fromEntries(verdier) }));
    }).catch(() => undefined);
    return () => { aktiv = false; };
  }, [boligId, boligbilder]);
  function krevInnlogging() { if (!innlogget) { window.location.assign("/logg-inn"); return true; } if (!kanRedigere) { setFeil("Du har lesetilgang og kan derfor ikke endre rom."); return true; } return false; }
  function nyttRom() { if (krevInnlogging()) return; setUtkast({ ...tomtRom, id: crypto.randomUUID(), bildeIder: [] }); setNyeBilder([]); setValgt(null); setRedigerer(true); setFeil(""); }
  function aapne(rommet: Rominfo) { setValgt(rommet); setUtkast({ ...rommet, bildeIder: rommet.bildeIder || [] }); setNyeBilder([]); setRedigerer(false); setFeil(""); }
  async function lagre() { if (!bolig || !data || !utkast.navn.trim()) { setFeil("Gi rommet et navn."); return; } setJobber(true); setFeil(""); try { const bildeIder = [...(utkast.bildeIder || [])]; for (const fil of nyeBilder) { bildeIder.push(await lastOppDokument(fil, { boligId: String(bolig.id), navn: `${utkast.navn.trim()} – bilde`, kategori: "boligbilde", ar: new Date().getFullYear(), dokumentdato: new Date().toISOString().slice(0, 10), notat: `Tilhører rom: ${utkast.id}` })); } const finnes = data.rom.some((rommet) => rommet.id === utkast.id); const ryddet = { ...utkast, navn: utkast.navn.trim(), bildeIder }; const nyListe = finnes ? data.rom.map((rommet) => rommet.id === ryddet.id ? ryddet : rommet) : [...data.rom, ryddet]; await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...data, rom: nyListe, oppdatert: new Date().toISOString() } }); await lastData(); setValgt(ryddet); setNyeBilder([]); setRedigerer(false); } catch { setFeil("Kunne ikke lagre rommet eller bildene."); } finally { setJobber(false); } }
  async function fordelFinnBilder() {
    if (!bolig || !data || krevInnlogging()) return;
    const brukte = new Set(data.rom.flatMap((rommet) => rommet.bildeIder || []));
    const finnBilder = boligbilder.filter((bilde) => /finn/i.test(`${bilde.navn} ${bilde.filnavn} ${bilde.notat}`) && !brukte.has(bilde.id));
    const mangler = data.rom.filter((rommet) => !(rommet.bildeIder || []).length).sort((a, b) => romPrioritet(a.navn) - romPrioritet(b.navn));
    if (!finnBilder.length || !mangler.length) { setFeil("Fant ingen ledige FINN-bilder eller rom uten bilder."); return; }
    const innendorsbilder = finnBilder.filter((bilde) => !bildeErUtvendig(bilde));
    const kandidater = innendorsbilder.length >= mangler.length ? innendorsbilder : finnBilder;
    const erLeilighet = /leilighet|hybel|studio/i.test(String(bolig.boligtype || ""));
    const antattUtvendigeForst = erLeilighet ? 0 : 2;
    const start = Math.min(antattUtvendigeForst, Math.max(0, kandidater.length - mangler.length));
    const ledige = [...kandidater.slice(start), ...kandidater.slice(0, start)];
    const koblinger = new Map<string, string>();
    for (const rommet of mangler) {
      const treff = ledige.findIndex((bilde) => bildePasserRom(bilde, rommet.navn));
      const indeks = treff >= 0 ? treff : 0;
      const bilde = ledige.splice(indeks, 1)[0];
      if (bilde) koblinger.set(rommet.id, bilde.id);
    }
    if (!koblinger.size) return;
    setJobber(true); setFeil("");
    try {
      const nyeRom = data.rom.map((rommet) => koblinger.has(rommet.id) ? { ...rommet, bildeIder: [koblinger.get(rommet.id)!] } : rommet);
      await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...data, rom: nyeRom, oppdatert: new Date().toISOString() } });
      await lastData();
    } catch { setFeil("Kunne ikke fordele FINN-bildene."); }
    finally { setJobber(false); }
  }
  useEffect(() => {
    const id = String(bolig?.id || "");
    if (!id || !innlogget || !kanRedigere || laster || !data || automatiskFordelt.current.has(id)) return;
    const harRomUtenBilde = data.rom.some((rommet) => !(rommet.bildeIder || []).length);
    const harFinnBilder = boligbilder.some((bilde) => /finn/i.test(`${bilde.navn} ${bilde.filnavn} ${bilde.notat}`));
    if (!harRomUtenBilde || !harFinnBilder) return;
    automatiskFordelt.current.add(id);
    void fordelFinnBilder();
  }, [bolig?.id, innlogget, kanRedigere, laster, data, boligbilder]);
  async function slett(rommet: Rominfo) { if (!bolig || !data || krevInnlogging() || !confirm(`Slett «${rommet.navn}»? Oppussingshistorikken beholdes.`)) return; setJobber(true); setFeil(""); try { const historikk = data.historikk.map((hendelse) => hendelse.romId === rommet.id ? { ...hendelse, romId: "", omrade: hendelse.omrade || rommet.navn } : hendelse); await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...data, rom: data.rom.filter((verdi) => verdi.id !== rommet.id), historikk, oppdatert: new Date().toISOString() } }); setValgt(null); setRedigerer(false); await lastData(); } catch { setFeil("Kunne ikke slette rommet."); } finally { setJobber(false); } }
  return <main className="privat-omrade min-h-screen overflow-x-hidden bg-stone-50 text-slate-900"><Navigasjon />
    <header className="bg-gradient-to-br from-emerald-100 via-stone-100 to-amber-50 px-4 py-10 sm:px-6"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold tracking-wider text-emerald-800">MITT HJEM</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-bold">Rom</h1><p className="mt-3 max-w-2xl text-slate-600">Finn fargekoder, materialer, notater og oppussingshistorikk for hvert rom.</p></div>{(!innlogget || kanRedigere) && <button type="button" onClick={nyttRom} className="min-h-12 rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white">+ Legg til rom</button>}</div></div></header>
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">{feil && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{feil}</p>}{laster ? <p className="py-16 text-center text-slate-500">Laster rom…</p> : !bolig ? <Tom /> : <><div className="grid gap-3 rounded-2xl bg-white p-4 shadow-sm sm:grid-cols-[240px_1fr]"><select value={String(bolig.id)} onChange={(event) => { setBoligId(event.target.value); setValgt(null); }} className="felt">{boliger.map((verdi) => <option key={verdi.id} value={verdi.id}>{String(verdi.adresse || "Privat bolig")}</option>)}</select><input value={sok} onChange={(event) => setSok(event.target.value)} placeholder="Søk etter rom, fargekode eller materiale" className="felt" /></div>
      <section className="mt-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Alle rom <span className="text-slate-400">({data?.rom.length || 0})</span></h2></div>{rom.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{rom.map((rommet, indeks) => { const forsidebilde = bilderFor(rommet)[0]; return <button key={rommet.id} type="button" onClick={() => aapne(rommet)} className="min-w-0 overflow-hidden rounded-2xl border border-stone-200 bg-white text-left shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300">{forsidebilde && bildelenker[forsidebilde.id] ? <img src={bildelenker[forsidebilde.id]} alt={rommet.navn} loading={indeks < 4 ? "eager" : "lazy"} fetchPriority={indeks < 2 ? "high" : "auto"} decoding="async" className="aspect-[4/3] w-full object-cover" /> : <div className="flex aspect-[4/3] items-center justify-center bg-stone-100 text-4xl">{romIkon(rommet.navn)}</div>}<div className="p-4"><h3 className="truncate font-bold">{rommet.navn}</h3><p className="mt-1 text-xs text-slate-500">{rommet.areal || "Areal ikke registrert"}</p>{(rommet.veggfarge || rommet.fargekode) && <div className="mt-3 rounded-lg bg-emerald-50 p-2"><span className="block text-[10px] font-bold uppercase text-emerald-700">Veggfarge</span><span className="mt-0.5 block truncate text-xs font-semibold">{[rommet.veggfarge, rommet.fargekode].filter(Boolean).join(" · ")}</span></div>}</div></button>; })}</div> : <div className="rounded-3xl border border-dashed border-stone-300 bg-white p-8 text-center"><p className="text-slate-500">Ingen rom funnet.</p>{(!innlogget || kanRedigere) && <button onClick={nyttRom} className="mt-4 font-bold text-emerald-700">+ Legg til ditt første rom</button>}</div>}</section>
      {data && data.rom.some((verdi) => verdi.veggfarge || verdi.fargekode) && <section className="mt-8 rounded-3xl bg-slate-950 p-5 text-white sm:p-7"><h2 className="text-xl font-bold">🎨 Fargekoder</h2><p className="mt-1 text-sm text-slate-400">Rask oversikt når du skal kjøpe maling eller flekke veggen.</p><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.rom.filter((verdi) => verdi.veggfarge || verdi.fargekode).map((rommet) => <button key={rommet.id} onClick={() => aapne(rommet)} className="rounded-xl bg-slate-900 p-4 text-left"><strong>{rommet.navn}</strong><span className="mt-1 block text-sm text-emerald-300">{rommet.veggfarge || "Uten fargenavn"}</span><span className="mt-0.5 block text-xs text-slate-400">{[rommet.fargekode, rommet.maling, rommet.glans && `Glans ${rommet.glans}`].filter(Boolean).join(" · ")}</span></button>)}</div></section>}</>}</div>
    {(valgt || redigerer) && <Modal tittel={redigerer ? (valgt ? "Rediger rom" : "Nytt rom") : valgt?.navn || "Rom"} onLukk={() => { setValgt(null); setRedigerer(false); setFeil(""); }}>{feil && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{feil}</p>}{redigerer ? <><Romskjema verdi={utkast} onEndre={setUtkast} tilgjengeligeBilder={boligbilder} bildelenker={bildelenker} nyeBilder={nyeBilder} onNyeBilder={setNyeBilder} /><button disabled={jobber} onClick={lagre} className="mt-6 min-h-12 w-full rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white disabled:opacity-50">{jobber ? "Lagrer…" : "Lagre rommet"}</button></> : valgt && <Romdetaljer rom={valgt} historikk={historikkFor(valgt)} bilder={bilderFor(valgt)} bildelenker={bildelenker} innlogget={innlogget && kanRedigere} onRediger={() => { setUtkast({ ...valgt, bildeIder: valgt.bildeIder || [] }); setRedigerer(true); }} onSlett={() => slett(valgt)} />}</Modal>}
  </main>;
}

function Romdetaljer({ rom, historikk, bilder, bildelenker, innlogget, onRediger, onSlett }: { rom: Rominfo; historikk: Historikkinfo[]; bilder: Dokument[]; bildelenker: Record<string, string>; innlogget: boolean; onRediger: () => void; onSlett: () => void }) { const detaljer = [["Areal", rom.areal], ["Veggfarge", rom.veggfarge], ["Fargekode", rom.fargekode], ["Maling", rom.maling], ["Glans", rom.glans], ["Gulv", rom.gulv], ["Tak", rom.tak], ["Lister", rom.lister], ["Sist pusset opp", rom.sistPusset]].filter(([, verdi]) => verdi); return <div>{bilder.length > 0 && <div className="mb-5 grid grid-cols-2 gap-2">{bilder.map((bilde, indeks) => bildelenker[bilde.id] && <img key={bilde.id} src={bildelenker[bilde.id]} alt={`${rom.navn} ${indeks + 1}`} className={indeks === 0 ? "col-span-2 aspect-video w-full rounded-2xl object-cover" : "aspect-square w-full rounded-xl object-cover"} />)}</div>}<dl className="grid gap-3 sm:grid-cols-2">{detaljer.map(([navn, verdi]) => <div key={navn} className={navn === "Fargekode" ? "rounded-xl bg-emerald-50 p-4 ring-1 ring-emerald-200" : "rounded-xl bg-stone-50 p-4"}><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{navn}</dt><dd className="mt-1 font-semibold">{verdi}</dd></div>)}</dl>{rom.notat && <div className="mt-4 rounded-xl bg-stone-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Notater</p><p className="mt-2 whitespace-pre-wrap text-sm">{rom.notat}</p></div>}<section className="mt-6"><h3 className="font-bold">Oppussing og historikk</h3>{historikk.length ? <div className="mt-2 divide-y rounded-xl border px-4">{historikk.map((hendelse) => <article key={hendelse.id} className="py-3"><strong>{hendelse.tittel}</strong><p className="mt-1 text-xs text-slate-500">{hendelse.dato}{hendelse.kostnad ? ` · ${new Intl.NumberFormat("nb-NO").format(hendelse.kostnad)} kr` : ""}</p></article>)}</div> : <p className="mt-2 text-sm text-slate-500">Ingen oppussing eller historikk er knyttet til rommet.</p>}</section>{innlogget && <div className="mt-6 flex flex-col gap-2 sm:flex-row"><button onClick={onRediger} className="min-h-12 flex-1 rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white">Rediger rommet</button><button onClick={onSlett} className="min-h-12 rounded-xl border border-red-200 px-5 py-3 font-bold text-red-600">Slett rom</button></div>}</div>; }
function Romskjema({ verdi, onEndre, tilgjengeligeBilder, bildelenker, nyeBilder, onNyeBilder }: { verdi: Rominfo; onEndre: (verdi: Rominfo) => void; tilgjengeligeBilder: Dokument[]; bildelenker: Record<string, string>; nyeBilder: File[]; onNyeBilder: (filer: File[]) => void }) {
  const felt = [["Navn på rommet *", "navn", "For eksempel stue"], ["Areal", "areal", "24 m²"], ["Veggfarge", "veggfarge", "Washed Linen"], ["Fargekode", "fargekode", "10679"], ["Maling / produkt", "maling", "Jotun Lady Pure Color"], ["Glans", "glans", "05"], ["Gulv", "gulv", "1-stavs eikeparkett"], ["Tak", "tak", "Farge eller materiale"], ["Lister", "lister", "Farge eller type"], ["Sist pusset opp", "sistPusset", "August 2026"]] as const;
  const valgte = verdi.bildeIder || [];
  function velgBilde(id: string) { onEndre({ ...verdi, bildeIder: valgte.includes(id) ? valgte.filter((bildeId) => bildeId !== id) : [...valgte, id] }); }
  function velgHovedbilde(id: string) { onEndre({ ...verdi, bildeIder: [id, ...valgte.filter((bildeId) => bildeId !== id)] }); }
  return <div className="grid gap-4 sm:grid-cols-2">{felt.map(([label, key, placeholder]) => <label key={key} className="text-sm font-semibold">{label}<input autoFocus={key === "navn"} value={verdi[key]} onChange={(event) => onEndre({ ...verdi, [key]: event.target.value })} placeholder={placeholder} className="felt mt-2" /></label>)}<label className="text-sm font-semibold sm:col-span-2">Notater<textarea rows={4} value={verdi.notat} onChange={(event) => onEndre({ ...verdi, notat: event.target.value })} className="felt mt-2" /></label><div className="sm:col-span-2"><p className="text-sm font-semibold">Bilder av rommet</p><p className="mt-1 text-xs text-slate-500">Velg bilder fra boligarkivet. Bildet merket «Hovedbilde» vises på romkortet.</p>{tilgjengeligeBilder.length > 0 ? <div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{tilgjengeligeBilder.map((bilde) => { const valgt = valgte.includes(bilde.id); const hovedbilde = valgte[0] === bilde.id; return <div key={bilde.id} className={`overflow-hidden rounded-xl border-2 ${valgt ? "border-emerald-500" : "border-stone-200"}`}>{bildelenker[bilde.id] ? <img src={bildelenker[bilde.id]} alt={bilde.navn} className="aspect-square w-full object-cover" /> : <div className="flex aspect-square items-center justify-center bg-stone-100 text-xs text-slate-500">Laster bilde…</div>}<div className="space-y-2 p-2"><button type="button" onClick={() => velgBilde(bilde.id)} className={`w-full rounded-lg px-2 py-2 text-xs font-bold ${valgt ? "bg-emerald-50 text-emerald-800" : "bg-stone-100 text-slate-700"}`}>{valgt ? "Valgt – fjern" : "Knytt til rommet"}</button>{valgt && <button type="button" disabled={hovedbilde} onClick={() => velgHovedbilde(bilde.id)} className="w-full rounded-lg border border-stone-200 px-2 py-2 text-xs font-bold text-slate-700 disabled:bg-emerald-500 disabled:text-white">{hovedbilde ? "Hovedbilde" : "Bruk som hovedbilde"}</button>}</div></div>; })}</div> : <p className="mt-3 rounded-xl bg-stone-50 p-4 text-sm text-slate-500">Ingen bilder ligger i boligarkivet ennå.</p>}<label className="mt-3 block rounded-xl border-2 border-dashed border-stone-300 p-4 text-center text-sm font-bold text-emerald-700">+ Ta eller last opp nye bilder<input type="file" accept="image/*" multiple onChange={(event) => onNyeBilder([...nyeBilder, ...Array.from(event.target.files || [])])} className="mt-3 block w-full text-xs text-slate-600" /></label>{nyeBilder.length > 0 && <p className="mt-2 text-xs text-slate-500">{nyeBilder.length} nye bilder klare for opplasting. Nye bilder legges sist; du kan velge hovedbilde etter lagring.</p>}</div></div>;
}
function Modal({ tittel, onLukk, children }: { tittel: string; onLukk: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-3"><div className="mx-auto my-4 max-w-2xl rounded-3xl bg-white p-5 shadow-2xl sm:my-10 sm:p-7"><div className="mb-6 flex items-center justify-between gap-4"><h2 className="text-2xl font-bold">{tittel}</h2><button onClick={onLukk} className="min-h-11 px-3 text-sm font-semibold text-slate-500">Lukk</button></div>{children}</div></div>; }
function Tom() { return <section className="rounded-3xl bg-white p-10 text-center shadow-sm"><h2 className="text-2xl font-bold">Ingen privat bolig</h2><p className="mt-2 text-slate-500">Opprett en privat bolig under Mitt hjem først.</p></section>; }
function romIkon(navn: string) { const verdi = navn.toLowerCase(); if (verdi.includes("bad") || verdi.includes("vask")) return "🚿"; if (verdi.includes("kjøkken")) return "🍳"; if (verdi.includes("soverom")) return "🛏️"; if (verdi.includes("stue")) return "🛋️"; if (verdi.includes("kontor")) return "💻"; if (verdi.includes("gang")) return "🚪"; if (verdi.includes("bod")) return "📦"; return "🏠"; }
function finnBildenummer(bilde: Dokument) { const treff = `${bilde.navn} ${bilde.filnavn}`.match(/(?:finn(?:-bilde)?\s*[- ]?)(\d+)/i); return treff ? Number(treff[1]) : Number.MAX_SAFE_INTEGER; }
function romPrioritet(navn: string) { const verdi = navn.toLowerCase(); if (verdi.includes("stue") || verdi.includes("kjøkken")) return 1; if (verdi.includes("soverom")) return 2; if (verdi.includes("bad") || verdi.includes("vask")) return 3; if (verdi.includes("gang") || verdi.includes("entr")) return 4; if (verdi.includes("loft") || verdi.includes("kjeller")) return 5; return 6; }
function bildePasserRom(bilde: Dokument, romnavn: string) { const tekst = `${bilde.navn} ${bilde.filnavn} ${bilde.notat}`.toLocaleLowerCase("nb-NO"); const rom = romnavn.toLocaleLowerCase("nb-NO"); const ord = rom.includes("stue") && rom.includes("kjøkken") ? ["stue", "kjøkken"] : rom.includes("soverom") ? [rom.replace(/\s+/g, " "), "soverom"] : rom.includes("bad") || rom.includes("vask") ? ["bad", "baderom", "vaskerom"] : rom.includes("gang") || rom.includes("entr") ? ["gang", "entré", "entre"] : rom.includes("loft") ? ["loft"] : rom.includes("kjeller") ? ["kjeller"] : [rom]; return ord.some((verdi) => tekst.includes(verdi)); }
function bildeErUtvendig(bilde: Dokument) { return /fasade|utvendig|hage|uteplass|terrasse|balkong|inngangsparti|drone/i.test(`${bilde.navn} ${bilde.filnavn} ${bilde.notat}`); }
