"use client";

import { useEffect, useMemo, useState } from "react";
import Navigasjon from "../components/Navigasjon";
import { demoAltOmBoligen, lesAltOmBoligen, type Historikkinfo, type Rominfo } from "../lib/alt-om-boligen";
import { hentBoliger, oppdaterBolig, type BoligData } from "../lib/boliger";
import { createClient } from "../lib/supabase/client";

const demoGrunnlag: BoligData = { id: "demo-privat-hjem", brukstype: "privat", adresse: "Eksempelveien 12, Bergen", boligtype: "Enebolig", byggeaar: "1958", areal: 142 };
const demoBolig: BoligData = { ...demoGrunnlag, altOmBoligen: demoAltOmBoligen(demoGrunnlag) };
const tomtRom: Rominfo = { id: "", navn: "", areal: "", veggfarge: "", fargekode: "", maling: "", glans: "", gulv: "", tak: "", lister: "", sistPusset: "", notat: "" };

export default function RomSide() {
  const [boliger, setBoliger] = useState<BoligData[]>([]); const [boligId, setBoligId] = useState(""); const [innlogget, setInnlogget] = useState(false); const [laster, setLaster] = useState(true); const [feil, setFeil] = useState("");
  const [valgt, setValgt] = useState<Rominfo | null>(null); const [redigerer, setRedigerer] = useState(false); const [utkast, setUtkast] = useState<Rominfo>(tomtRom); const [jobber, setJobber] = useState(false); const [sok, setSok] = useState("");
  async function lastData() { setLaster(true); setFeil(""); try { const { data } = await createClient().auth.getUser(); const erInnlogget = Boolean(data.user); setInnlogget(erInnlogget); const alle = erInnlogget ? await hentBoliger() : [demoBolig]; const privateBoliger = alle.filter((bolig) => String(bolig.brukstype || "") === "privat"); setBoliger(privateBoliger); setBoligId((gammel) => privateBoliger.some((bolig) => bolig.id === gammel) ? gammel : String(privateBoliger[0]?.id || "")); } catch { setFeil("Kunne ikke hente rommene."); } finally { setLaster(false); } }
  useEffect(() => { lastData(); }, []);
  const bolig = boliger.find((verdi) => String(verdi.id) === boligId) || boliger[0]; const data = bolig ? lesAltOmBoligen(bolig) : null;
  const rom = useMemo(() => (data?.rom || []).filter((verdi) => `${verdi.navn} ${verdi.veggfarge} ${verdi.fargekode} ${verdi.gulv}`.toLowerCase().includes(sok.toLowerCase())), [data, sok]);
  const historikkFor = (rommet: Rominfo): Historikkinfo[] => (data?.historikk || []).filter((hendelse) => hendelse.romId === rommet.id || (!hendelse.romId && hendelse.omrade.trim().toLowerCase() === rommet.navn.trim().toLowerCase())).sort((a, b) => b.dato.localeCompare(a.dato));
  function krevInnlogging() { if (innlogget) return false; window.location.assign("/logg-inn"); return true; }
  function nyttRom() { if (krevInnlogging()) return; setUtkast({ ...tomtRom, id: crypto.randomUUID() }); setValgt(null); setRedigerer(true); setFeil(""); }
  function aapne(rommet: Rominfo) { setValgt(rommet); setUtkast({ ...rommet }); setRedigerer(false); setFeil(""); }
  async function lagre() { if (!bolig || !data || !utkast.navn.trim()) { setFeil("Gi rommet et navn."); return; } setJobber(true); setFeil(""); try { const finnes = data.rom.some((rommet) => rommet.id === utkast.id); const ryddet = { ...utkast, navn: utkast.navn.trim() }; const nyListe = finnes ? data.rom.map((rommet) => rommet.id === ryddet.id ? ryddet : rommet) : [...data.rom, ryddet]; await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...data, rom: nyListe, oppdatert: new Date().toISOString() } }); await lastData(); setValgt(ryddet); setRedigerer(false); } catch { setFeil("Kunne ikke lagre rommet."); } finally { setJobber(false); } }
  async function slett(rommet: Rominfo) { if (!bolig || !data || krevInnlogging() || !confirm(`Slett «${rommet.navn}»? Oppussingshistorikken beholdes.`)) return; setJobber(true); setFeil(""); try { const historikk = data.historikk.map((hendelse) => hendelse.romId === rommet.id ? { ...hendelse, romId: "", omrade: hendelse.omrade || rommet.navn } : hendelse); await oppdaterBolig(String(bolig.id), { ...bolig, altOmBoligen: { ...data, rom: data.rom.filter((verdi) => verdi.id !== rommet.id), historikk, oppdatert: new Date().toISOString() } }); setValgt(null); setRedigerer(false); await lastData(); } catch { setFeil("Kunne ikke slette rommet."); } finally { setJobber(false); } }
  return <main className="min-h-screen bg-stone-50 text-slate-900"><Navigasjon />
    <header className="bg-gradient-to-br from-emerald-100 via-stone-100 to-amber-50 px-4 py-10 sm:px-6"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold tracking-wider text-emerald-800">MITT HJEM</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-bold">Rom</h1><p className="mt-3 max-w-2xl text-slate-600">Finn fargekoder, materialer, notater og oppussingshistorikk for hvert rom.</p></div><button type="button" onClick={nyttRom} className="min-h-12 rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white">+ Legg til rom</button></div></div></header>
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">{feil && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{feil}</p>}{laster ? <p className="py-16 text-center text-slate-500">Laster rom…</p> : !bolig ? <Tom /> : <><div className="grid gap-3 rounded-2xl bg-white p-4 shadow-sm sm:grid-cols-[240px_1fr]"><select value={String(bolig.id)} onChange={(event) => { setBoligId(event.target.value); setValgt(null); }} className="felt">{boliger.map((verdi) => <option key={verdi.id} value={verdi.id}>{String(verdi.adresse || "Privat bolig")}</option>)}</select><input value={sok} onChange={(event) => setSok(event.target.value)} placeholder="Søk etter rom, fargekode eller materiale" className="felt" /></div>
      <section className="mt-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Alle rom <span className="text-slate-400">({data?.rom.length || 0})</span></h2></div>{rom.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{rom.map((rommet) => <button key={rommet.id} type="button" onClick={() => aapne(rommet)} className="rounded-2xl border border-stone-200 bg-white p-4 text-left shadow-sm transition hover:border-emerald-300 hover:-translate-y-0.5"><span className="text-3xl">{romIkon(rommet.navn)}</span><h3 className="mt-3 truncate font-bold">{rommet.navn}</h3><p className="mt-1 text-xs text-slate-500">{rommet.areal || "Areal ikke registrert"}</p>{(rommet.veggfarge || rommet.fargekode) && <div className="mt-3 rounded-lg bg-emerald-50 p-2"><span className="block text-[10px] font-bold uppercase text-emerald-700">Veggfarge</span><span className="mt-0.5 block truncate text-xs font-semibold">{[rommet.veggfarge, rommet.fargekode].filter(Boolean).join(" · ")}</span></div>}</button>)}</div> : <div className="rounded-3xl border border-dashed border-stone-300 bg-white p-8 text-center"><p className="text-slate-500">Ingen rom funnet.</p><button onClick={nyttRom} className="mt-4 font-bold text-emerald-700">+ Legg til ditt første rom</button></div>}</section>
      {data && data.rom.some((verdi) => verdi.veggfarge || verdi.fargekode) && <section className="mt-8 rounded-3xl bg-slate-950 p-5 text-white sm:p-7"><h2 className="text-xl font-bold">🎨 Fargekoder</h2><p className="mt-1 text-sm text-slate-400">Rask oversikt når du skal kjøpe maling eller flekke veggen.</p><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.rom.filter((verdi) => verdi.veggfarge || verdi.fargekode).map((rommet) => <button key={rommet.id} onClick={() => aapne(rommet)} className="rounded-xl bg-slate-900 p-4 text-left"><strong>{rommet.navn}</strong><span className="mt-1 block text-sm text-emerald-300">{rommet.veggfarge || "Uten fargenavn"}</span><span className="mt-0.5 block text-xs text-slate-400">{[rommet.fargekode, rommet.maling, rommet.glans && `Glans ${rommet.glans}`].filter(Boolean).join(" · ")}</span></button>)}</div></section>}</>}</div>
    {(valgt || redigerer) && <Modal tittel={redigerer ? (valgt ? "Rediger rom" : "Nytt rom") : valgt?.navn || "Rom"} onLukk={() => { setValgt(null); setRedigerer(false); setFeil(""); }}>{feil && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{feil}</p>}{redigerer ? <><Romskjema verdi={utkast} onEndre={setUtkast} /><button disabled={jobber} onClick={lagre} className="mt-6 min-h-12 w-full rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white disabled:opacity-50">{jobber ? "Lagrer…" : "Lagre rommet"}</button></> : valgt && <Romdetaljer rom={valgt} historikk={historikkFor(valgt)} innlogget={innlogget} onRediger={() => { setUtkast({ ...valgt }); setRedigerer(true); }} onSlett={() => slett(valgt)} />}</Modal>}
  </main>;
}

function Romdetaljer({ rom, historikk, innlogget, onRediger, onSlett }: { rom: Rominfo; historikk: Historikkinfo[]; innlogget: boolean; onRediger: () => void; onSlett: () => void }) { const detaljer = [["Areal", rom.areal], ["Veggfarge", rom.veggfarge], ["Fargekode", rom.fargekode], ["Maling", rom.maling], ["Glans", rom.glans], ["Gulv", rom.gulv], ["Tak", rom.tak], ["Lister", rom.lister], ["Sist pusset opp", rom.sistPusset]].filter(([, verdi]) => verdi); return <div><dl className="grid gap-3 sm:grid-cols-2">{detaljer.map(([navn, verdi]) => <div key={navn} className={navn === "Fargekode" ? "rounded-xl bg-emerald-50 p-4 ring-1 ring-emerald-200" : "rounded-xl bg-stone-50 p-4"}><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{navn}</dt><dd className="mt-1 font-semibold">{verdi}</dd></div>)}</dl>{rom.notat && <div className="mt-4 rounded-xl bg-stone-50 p-4"><p className="text-xs font-bold uppercase text-slate-400">Notater</p><p className="mt-2 whitespace-pre-wrap text-sm">{rom.notat}</p></div>}<section className="mt-6"><h3 className="font-bold">Oppussing og historikk</h3>{historikk.length ? <div className="mt-2 divide-y rounded-xl border px-4">{historikk.map((hendelse) => <article key={hendelse.id} className="py-3"><strong>{hendelse.tittel}</strong><p className="mt-1 text-xs text-slate-500">{hendelse.dato}{hendelse.kostnad ? ` · ${new Intl.NumberFormat("nb-NO").format(hendelse.kostnad)} kr` : ""}</p></article>)}</div> : <p className="mt-2 text-sm text-slate-500">Ingen historikk er knyttet til rommet.</p>}</section>{innlogget && <div className="mt-6 flex flex-col gap-2 sm:flex-row"><button onClick={onRediger} className="min-h-12 flex-1 rounded-xl bg-emerald-500 px-5 py-3 font-bold text-white">Rediger rommet</button><button onClick={onSlett} className="min-h-12 rounded-xl border border-red-200 px-5 py-3 font-bold text-red-600">Slett rom</button></div>}</div>; }
function Romskjema({ verdi, onEndre }: { verdi: Rominfo; onEndre: (verdi: Rominfo) => void }) { const felt = [["Navn på rommet *", "navn", "For eksempel stue"], ["Areal", "areal", "24 m²"], ["Veggfarge", "veggfarge", "Washed Linen"], ["Fargekode", "fargekode", "10679"], ["Maling / produkt", "maling", "Jotun Lady Pure Color"], ["Glans", "glans", "05"], ["Gulv", "gulv", "1-stavs eikeparkett"], ["Tak", "tak", "Farge eller materiale"], ["Lister", "lister", "Farge eller type"], ["Sist pusset opp", "sistPusset", "August 2026"]] as const; return <div className="grid gap-4 sm:grid-cols-2">{felt.map(([label, key, placeholder]) => <label key={key} className="text-sm font-semibold">{label}<input autoFocus={key === "navn"} value={verdi[key]} onChange={(event) => onEndre({ ...verdi, [key]: event.target.value })} placeholder={placeholder} className="felt mt-2" /></label>)}<label className="text-sm font-semibold sm:col-span-2">Notater<textarea rows={4} value={verdi.notat} onChange={(event) => onEndre({ ...verdi, notat: event.target.value })} className="felt mt-2" /></label></div>; }
function Modal({ tittel, onLukk, children }: { tittel: string; onLukk: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-3"><div className="mx-auto my-4 max-w-2xl rounded-3xl bg-white p-5 shadow-2xl sm:my-10 sm:p-7"><div className="mb-6 flex items-center justify-between gap-4"><h2 className="text-2xl font-bold">{tittel}</h2><button onClick={onLukk} className="min-h-11 px-3 text-sm font-semibold text-slate-500">Lukk</button></div>{children}</div></div>; }
function Tom() { return <section className="rounded-3xl bg-white p-10 text-center shadow-sm"><h2 className="text-2xl font-bold">Ingen privat bolig</h2><p className="mt-2 text-slate-500">Opprett en privat bolig under Mitt hjem først.</p></section>; }
function romIkon(navn: string) { const verdi = navn.toLowerCase(); if (verdi.includes("bad") || verdi.includes("vask")) return "🚿"; if (verdi.includes("kjøkken")) return "🍳"; if (verdi.includes("soverom")) return "🛏️"; if (verdi.includes("stue")) return "🛋️"; if (verdi.includes("kontor")) return "💻"; if (verdi.includes("gang")) return "🚪"; if (verdi.includes("bod")) return "📦"; return "🏠"; }
